### DISCUSSION TITLE
Recursive partials in templates?

### DISCUSSION THREAD

**Discussion by AdamantGarth** [jgm/pandoc#10008] [Q&A]
I have a pandoc template that should render a recursive structure. Here's a minimal example:

###### `template.tmpl`
```
This is a recursive list of stuff:
$stuff:recursive()$
```

###### `recursive.tmpl`
```
$if(it.value)$
- $it.name$: $it.value$
$else$
- $it.name$:
    $it.sub:recursive()$
$endif$
```

###### `data.yml`
```yaml
title: ':('
stuff:
  - name: Alpha
    value: Lorem
  - name: Bravo
    value: ipsum
  - name: Charlie
    sub:
      - name: Delta
        value: dolor
      - name: Echo
        value: sit
      - name: Foxtrot
        sub:
          - name: Golf
            value: amet
          - name: Hotel
            value: consectetur
```

I edited down the amount of foxtrots, but otherwise the result looks like this:
```
$ pandoc -f gfm --metadata-file data.yml --template template.tmpl /dev/null
This is a recursive list of stuff:
- Alpha: Lorem
- Bravo: ipsum
- Charlie:
    - Delta: sit
    - Echo: amet
    - Foxtrot:
        - Foxtrot:
            - Foxtrot:
                - Foxtrot:
                    - Foxtrot:
                        - Foxtrot:
                            - Foxtrot:
                                - Foxtrot:
                                    (loop)
```

It's nice that pandoc caught an infinite recursion here and stopped it with a `(loop)` entry. But I'm not sure what causes it. The first level of recursion seems to work fine (Charlie got expanded correctly), problem starts with the second level. I'm also not sure if this is an issue with pandoc, or if I'm just using partials wrong :)
