### DISCUSSION TITLE
pandoc --citeproc throws parse exception error on pandoc generated bibliography

### DISCUSSION THREAD

**Discussion by amunn** [jgm/pandoc#10151] [Q&A]
I'm using `pandoc` to generate an html bibliography from a `.bib` file. It's a two step process:

```
pandoc lab-publications.bib -s -f biblatex -t markdown -o lab-pubs.txt
pandoc --citeproc --csl apa-cv lab-pubs.txt -o tmp-bib.html

```
This was working fine, but suddenly has stopped working, and I get the following error on running the second step:

```
YAML parse exception at line 0, column 0:
control characters are not allowed
```

I'm assuming that there's something in the `.bib` file so that the output of the first step is ill-formed, but that output looks ok AFAICS. I don't really know how to go about debugging this, short of trimming the bib entries one by one. It's also strange that the the first step always works, so I would have thought that the output would be valid YAML, since `pandoc` generated it.

Any suggestions on how to solve this?

The actual `.bib` file can be found [here](https://github.com/msu-language-acquisition-lab/msu-language-acquisition-lab.github.io/tree/5fb3cbe3d37db04f22e5d186cd7318035dee62d1/pages/publications).

**Comment by amunn** [comment]
So it turns out that one of the imported `.bib` entries had the character â in it, which was fine for step 1 but bad for step 2. It would be nice if such characters could be flagged in the conversion from bibtex to YAML.

**Reply by jgm** [reply]
Can you create a YAML from just that one bib entry, so I can look at the generated YAML?

**Comment by amunn** [comment]
Here's the `.bib` file entry: (this is what I get from pasting the DOI into BibDesk, which retrieves the entry automatically)

```
@article{Miller_2012,
	author = {Miller, Karen L. and Schmitt, Cristina},
	date-added = {2024-09-04 12:21:52 -0400},
	date-modified = {2024-09-04 12:21:52 -0400},
	doi = {10.1080/10489223.2012.685026},
	issn = {1532-7817},
	journal = {Language Acquisition},
	month = jun,
	number = {3},
	pages = {223â261},
	publisher = {Informa UK Limited},
	title = {Variable Input and the Acquisition of Plural Morphology},
	url = {http://dx.doi.org/10.1080/10489223.2012.685026},
	volume = {19},
	year = {2012},
	bdsk-url-1 = {http://dx.doi.org/10.1080/10489223.2012.685026}}
```

And here's the generated YAML:

```
---
nocite: "[@*]"
references:
- author:
  - family: Miller
    given: Karen L.
  - family: Schmitt
    given: Cristina
  container-title: Language Acquisition
  doi: 10.1080/10489223.2012.685026
  id: Miller_2012
  issn: 1532-7817
  issue: 3
  issued: 2012-06
  page: 223â261
  publisher: Informa UK Limited
  title: Variable input and the acquisition of plural morphology
  type: article-journal
  url: "http://dx.doi.org/10.1080/10489223.2012.685026"
  volume: 19
---

```
