### DISCUSSION TITLE
ANN: pandoc/actions/setup@v1.1

### DISCUSSION THREAD

**Discussion by tarleb** [jgm/pandoc#10296] [Show and tell]
I'm happy to announce a new release of pandoc/actions for GitHub Actions. It is a helper to setup pandoc in CI actions and now works on Linux, macOS, and Windows runners.

## Usage:

Place this in your workflow YAML to use the latest official pandoc binary:

``` yaml
jobs:
  pandoc:
    steps:
      - name: Install pandoc
        uses: pandoc/actions/setup@v1

      - name: Run pandoc
        run: pandoc --version
```

A specific pandoc version can be chosen via the `version` argument:

``` yaml
      - name: Install pandoc
        uses: pandoc/actions/setup@v1
        with: {version: 3.5}
```

The sources are here: https://github.com/pandoc/actions
