### DISCUSSION TITLE
Template variables: How to access field of last element in array?

### DISCUSSION THREAD

**Discussion by rnwst** [jgm/pandoc#10757] [Q&A] [answered]
I have a variable that is defined in frontmatter as follows:
```yaml
list:
  - id: 1
    name: Geoff
  - id: 2
    name: Alex
```
In the template, I want to access the `name` of the last element in `list`. I have tried this:
```
$if(list)$$list/last.name$$endif$
```
However, this throws an error when running pandoc with this template:
```
unexpected "."
expecting "/", "(", ":", "[" or "$"
```
