### DISCUSSION TITLE
Shouldn't in-document metadata override defaults file metadata?

### DISCUSSION THREAD

**Discussion by bpj** [jgm/pandoc#10780] [Q&A]
In a defaults file
`$PANDOC_DATA_DIR/defaults/lualatex.yaml` I have

```yaml
metadata:
  mainfont: Noto Serif
  sansfont: Noto Sans
  monofont: Noto Sans Mono
```

In the metadata block of my Markdown file I have:

```yaml
mainfont: Charis SIL
```

The generated LaTeX has Noto Serif as mainfont which is
not what I expect, as I thought that the metadata in
the Markdown file should have higher priority.

I can work around this by creating a file `charis.yaml` containing just

```yaml
metadata:
  mainfont: Charis SIL
```

and using the commandline

    pandoc -d lualatex.yaml -d charis.yaml -o mydoc.pdf mydoc.md
    
but should it really be necessary?

pandoc 3.6.4
