### DISCUSSION TITLE
pandoc-server in docker

### DISCUSSION THREAD

**Discussion by Mamedov14** [jgm/pandoc#9456] [General]
Hi, I want to deploy pandoc-server in docker

I was able to do this locally using the documentation [pandoc](https://pandoc.org/installing.html) and [pandoc-server](https://pandoc.org/pandoc-server.html)

But now I would like to do this in Docker so that I can access my service via the API

My docker-compose.yml
```yml
version: "3"

services:
  pandoc-server:
    image: pandoc/core:3.1.1
    container_name: pandoc-server
    command: pandoc-server -p 8080
    ports:
      - "8080:8080"
    volumes:
      - ./path/mdToDocx:/app
```

I don't understand why there is no pandoc-server in the pandoc/core image
When I run docker-compose up I get an error
```
pandoc-server  | [WARNING] Could not deduce format from file extension  or 
pandoc-server  |   Defaulting to markdown
pandoc-server  | pandoc: pandoc-server: openBinaryFile: does not exist (No such file or directory)
pandoc-server exited with code 1
```

Please tell me if anyone knows how to run pandoc-server in docker

Thank you!

**Comment by jgm** [comment]
pandoc-server (when it exists) is merely a symlink to pandoc.  When pandoc runs it checks the name under which it is run, and if it's pandoc-server, it runs in server mode.

However, you need not worry about that.  Just do
```
pandoc server -p 8080
```

**Reply by Mamedov14** [reply]
Thank you very much for the answer!

Yes, I understand that when we do `pandoc server -p 8080` it starts in server mode
Locally it works great
But when I try to do exactly the same thing in docker using the `pandoc/core:3.1.1` image, it doesn't work

I searched for a long time and did not find any reason why the error occurs with `pandoc: pandoc: openBinaryFile: does not exist (No such file or directory)`
Maybe you know what this might be connected with?

**Reply by jgm** [reply]
OK, my comment was just about using `pandoc server` instead of `pandoc-server`.
It is possible that the version of pandoc in the Docker image was compiled without `+server` support.
@tarleb can you clarify this?

**Reply by jgm** [reply]
See also https://github.com/pandoc/dockerfiles

**Reply by Mamedov14** [reply]
Thanks again for your answers

I have now carefully re-read the `README.md` in https://github.com/pandoc/dockerfiles

And I noticed important words in this paragraph
```
It may look weird to you that you can just add README.md at the end of this line, but that's just because the pandoc/latex:2.6 
will simply prepend pandoc in front of anything you write after pandoc/latex:2.6 (this is known as the ENTRYPOINT field of the Dockerfile). 
So what you're really running here is pandoc README.md, which is a valid pandoc command.
```

I modified `docker-compose.yml` and everything worked!)
```yaml
version: "3"

services:
  pandoc-server:
    image: pandoc/core:3.1.1
    container_name: pandoc-server
    command: server -p 8080
    ports:
      - "8080:8080"
    volumes:
      - ./path/mdToDocx:/app
```

It turns out that `pandoc/core:3.1.1` substitutes `pandoc` itself and this starts the server
