### DISCUSSION TITLE
Specify pandoc-crossref in YAML default file

### DISCUSSION THREAD

**Discussion by AlexLietard** [jgm/pandoc#9628] [Q&A] [answered]
Hello everyone,

I've been wondering whether it's possible to specify the option `--filter=pandoc-crossref` in the default YAML file. This would result in something like:

```yaml
citeproc: true
csl: apa.csl
filter: pandoc-crossref
```

However, currently, I encountered an error: `eson exception: Error in $: Unknown option "filter"`.

Thank you for the time you will dedicate to it,
