### DISCUSSION TITLE
How can I prevent Pandoc from escaping braces in template variables for LaTeX?

### DISCUSSION THREAD

**Discussion by sh9temp** [jgm/pandoc#9694] [Q&A] [answered]
# TL;DR
Want to stop this:
```bash
$ echo >temp.md '$x$'
$ echo >test.md '---
  x: a{b}c
  ---'
$ pandoc --template temp.md test.md -t markdown
a{b}c
$ pandoc --template temp.md test.md -t latex
a\{b\}c
```
How can I do that?
# Details
I need LaTeX preamble like this:
```latex
\setmainjfont[
  CharacterWidth=Proportional,
  YokoFeatures={JFM=prop},
  UprightFont={*-Regular},
  BoldFont={*-Bold}]{__font__}
```
So, I wrote this:
```yaml
---
CJKfontoptions:
- CharacterWidth=Proportional
- YokoFeatures={JFM=prop}
- UprightFont={*-Regular}
- BoldFont={*-Bold}
...
```
But, I got this:
```latex
\setmainjfont[
  CharacterWidth=Proportional,
  YokoFeatures=\{JFM=prop\},
  UprightFont=\{*-Regular\},
  BoldFont=\{*-Bold\}]{__font__}
```
This causes an error.

**Comment by tarleb** [comment, marked as answer]
Pandoc won't escape strings if

1. it knows that it's raw LaTeX, e.g.

    ``` yaml
    ---
    CJKfontoptions:
    - `CharacterWidth=Proportional`{=latex}
    - `YokoFeatures={JFM=prop}`{=latex}
    ...

    or

2. the strings are variable values, defined, for example, in a [defaults file](https://pandoc.org/MANUAL.html#defaults-files)

    ``` yaml
    variables:
      CJKfontoptions:
        - CharacterWidth=Proportional
        - YokoFeatures={JFM=prop}
    ```
