### DISCUSSION TITLE
Running filters consecutively

### DISCUSSION THREAD

**Discussion by avidseeker** [jgm/pandoc#9814] [Q&A] [answered]
Here is a defaults file I use for proofreading with scripts taken from https://github.com/pandoc/lua-filters

```yaml
from: markdown
to: markdown
output-file: '/dev/null'
verbosity: INFO
filters:
  - spell.lua
  - wc.lua
```

* Expected: Show output of spell.lua, then show wordcount.
* Result: Only output of the first filter I put is shown
* Note: both filters work individually, but when I put then consecutively only the first works.
