### DISCUSSION TITLE
Html --> Word with page breaks

### DISCUSSION THREAD

**Discussion by vineshghela** [jgm/pandoc#9869] [Q&A] [answered]
Hey Everyone ive got a html file and i want to convert it to word for the most part it is working. However i want to add page break e.g. cover sheet followed by table of contents and then the contents of the file. Ive been searching through forums and I seem seem to be hitting a brick wall.

I was wondering if you were able to help 

i have tried the following

the css for the class new-page is the same as ` page-break-before: always;`

```
<h1> First page</h1>
  <div class="new-page"></div> 
        <w:br w:type="page"/>
   <div style="page-break-before: always;"></div>
<h1> Contents</h1>
```

**Comment by jgm** [comment]
It's not possible to include OpenXML elements in HTML and have pandoc recognize them as such.
Your best bet is to use a regular HTML element, such as your `<div class="new-page"></div>`, which will be parsed as a pandoc Div.  Then use a Lua filter to replace this Div with some suitable OpenXML code when FORMAT is docx.

**Reply by vineshghela** [reply]
The OpenXML sytax was when i just got tired of hitting the brick wall  :( 

Thank you so much for the advice ill take a look into it!

**Comment by tarleb** [comment, marked as answer]
Try the latest version of the [pagebreak filter](https://github.com/pandoc-ext/pagebreak) and configure it with these settings

``` yaml
---
pagebreak:
  break-on:
    # Allow plaintext commands, i.e., respect LaTeX newpage
    # commands even if they are not in a raw TeX block.
    plaintext-command: true
---
```

Then use `<p>\newpage</p>` in your HTML.
