### DISCUSSION TITLE
How to set "canonical" version using <link rel="canonical" href="...../$file" /> ?

### DISCUSSION THREAD

**Discussion by OLDlayeratwork** [jgm/pandoc#9961] [Q&A]
We generate our documentation with pandoc and Google is complaining about the fact we have no canonical version set, since we have multiple versions of the documentation and they want to know which one is canonical.  This is done via 

```
<link rel="canonical" href="/path/to/doc/version/function.html" />
```

The source is in Markdown and I tried adding this to the `.md` files but it did not work (the code doesn't appear in the output `.html` file):

```
header-includes:
  <link rel="canonical" href="/support/documentation/current/foo.html" />
```

Ideas?  IMO, it would be a very nice feature to add to pandoc to add this to `<head>...</head>` automatically.

**Comment by OLDlayeratwork** [comment]
Using this version of pandoc:
```
pandoc 2.13
Compiled with pandoc-types 1.22, texmath 0.12.2, skylighting 0.10.5,
citeproc 0.3.0.9, ipynb 0.1.0.1
```

**Comment by OLDlayeratwork** [comment]
I've tried a lot of variations and I can't get it to pass anything to the `.html` file.  Here's my command:
```
pandoc -s --toc --from=gfm --to=html --css acldoc-styles.css -H header.html -A footer.html -A header-foot.html -o foo.html foo.md
```
and here's what I think should work, using the documentation as a guide:
```
---
title: Foo
header-includes:
- |
  \`\`\`
  <link rel="canonical" href="/support/documentation/current/foo.html" />
  \`\`\`
---
```
Ignore the backslashes before the triple backquotes.

**Reply by jgm** [reply]
What you want is
````
---
title: Foo
header-includes:
- |
  ```{=html}
  <link rel="canonical" href="/support/documentation/current/foo.html" />
  ```
---
````

**Reply by jgm** [reply]
Or just
````
---
title: Foo
header-includes:
- |
  <link rel="canonical" href="/support/documentation/current/foo.html" />
---
````

**Comment by OLDlayeratwork** [comment]
I decided to write a script to add the proper HTML to the output file.  Not optimal, but a simple fix.

I realize this whole issue was created by Google and the developers might not want to add a "fix" for this to pandoc.  That's fine, I would understand.

I do think the fact that I can't add things to the `<head> ... </head>` is a bug, since the documentation indicates I should be able to do it.

**Comment by badumont** [comment]
Your version of Pandoc is very old. Using the latest version, the method tried in your first message works.

**Comment by tarleb** [comment]
The issue here is that the `-H` option overrides the `header-includes` in the YAML metadata. I seem to remember that there is an issue for that somewhere.

**Reply by tarleb** [reply]
The issue is #3139

**Reply by bpj** [reply]
It is pretty easy to modify your local (possibly local default) templates for any sets of includes which don’t interact with `--include-in-header`, for example in your latex template:

after `]{$documentclass$}`

``` pandoc-template
$for(before-header.latex)$
$before-header.latex$
$endfor$
```

and then just before `$for(header-includes)$`

``` pandoc-template
$for(after-header.latex)$
$after-header.latex$
$endfor$
```

(See [Templates in the Pandoc manual]!)

  [Templates in the Pandoc manual]: https://pandoc.org/MANUAL.html#templates

and then in your metadata:

```` yaml
before-header:
  latex:
    - |
      ```{=latex}
      \usepackage{mypackage}
      \include{myinclude.ltx}
      ```
  html:
    - |
      ```{=html}
      <link rel="stylesheet" href="mystyle.css" />
      ```
after-header:
  html:
    - |
      ```{=html}
      <style>
      .red { color: red }
      </style>
      ```
````

Note that you still have to wrap the actual markup in raw blocks to avoid Markdown escaping! Or you could put it in a defaults file like this to avoid that:

(See [Defaults files in the Pandoc manual]!)

  [Defaults files in the Pandoc manual]: https://pandoc.org/MANUAL.html#defaults-files

``` yaml
variables:
  before-header:
    latex:
      - |
        \usepackage{mypackage}
        \include{myinclude.ltx}
    html:
      - |
        <link rel="stylesheet" href="mystyle.css" />
  after-header:
    html:
      - |
        <style>
        .red { color: red }
        </style>
```

You can of course also have `$for(before-body)$` etc. or organize it even more hierarchically however you want:

``` yaml
  includes:
    latex:
      header:
        before:
          # list of markup blocks
        after:
          # list of markup blocks
      body:
        before:
          # list of markup blocks
        after:
          # list of markup blocks
    html:
      # You get the idea
```

and then in your latex template

``` pandoc-template
$for(includes.latex.header.before)$
$includes.latex.header.before$
$endfor$
```

etc.

Of course in your html template you could have

``` html
$for(link-css)$
<link rel="stylesheet" href="$link-css$" />
$endfor$
$if(css-style)$
<style>
$for(css-style)$
$css-style$
$endfor$
</style>
$endif$
```

and then in your defaults file

``` yaml
variables:
  link-css:
    - mystyle.css
  css-style:
    - |
      .red { color: red }
```

In other words you can include anything from metadata and variables you like however you like in your templates, and as long as you use other names than those variables which pandoc associates with its commandline options your custom fields will be totally independent. In my custom latex template I for example have:

``` latex
$for(ltx-pkg)$
$if(ltx-pkg.opts)$
\usepackage[$--
$for(ltx-pkg.opts)$
  $ltx-pkg.opts$$sep$,
$endfor$
]{$ltx-pkg.name$}
$else$
\usepackage{$if(ltx-pkg.name)$$ltx-pkg.name$$else$$ltx-pkg$$endif$}
$endif$
$endfor$
```

which with this in a defaults file

``` yaml
variables:
  ltx-pkg:
    - foopack
    - name: ulem
      opts: normalem
    - name: mypack
      opts:
        - tic=tac
        - toc
        - tuc
    - name: barpack
```

gives this in my latex header

``` latex
\usepackage{foopack}
\usepackage[
  normalem]{ulem}
\usepackage[
  tic=tac,
  toc,
  tuc]{mypack}
\usepackage{barpack}
```

Now I guess someone ought to make a PR for adding all those `$for(includes.format.header.before)$` etc. to all the builtin templates, and I guess that could be me, but frankly its a lot of work because there are a lot of templates for a lot of formats, and I don’t even know what it would look like for all formats, or where it makes sense to place them for which formats. Maybe I could create a branch for this in my pandoc repository fork and ask people to contribute, but I guess that should include tests, and I don’t even know where to start with those!
