### ISSUE TITLE
Allow user styling of ANSI writer output

### ISSUE THREAD

**Issue by silby** [jgm/pandoc#10150]
The ANSI writer, of necessity, has a bunch of hardcoded aesthetic decisions, as discussed in the review history of #9565. There should be an API to provide a stylesheet to the ANSI writer and a user interface for constructing such stylesheets/overriding parts of the default, using e.g. the defaults file.

The stylesheet could look something like:

```haskell
data Stylesheet = Stylesheet {
    styleCode :: Doc Text -> Doc Text,
    styleBullet :: Text,
    styleBlockQuoteBorder :: Text,
    styleH1 :: Doc Text -> Doc Text,
    -- and so on
}
```

The user interface could look something like:

```yaml
ansi_style:
 code:
   bg: white
   fg: red
 h1:
   weight: bold
   align: center
```
