### ISSUE TITLE
Issue setting a variable of type Dictionary from the command line

### ISSUE THREAD

**Issue by ZoomRmc** [jgm/pandoc#10298]
I have a trouble setting up a variable of a type Dictionary from the command line.
From what I see in the docs, there's only [one such variable](https://pandoc.org/MANUAL.html#variables-for-typst), namely the `margin` for typst.

There's no problem setting it with the defaults YAML, but I'm not sure if pandoc currently can parse a dictionary from the command line. 
The issue is exacerbated by a total lack of any error feedback on incorrectly formatted options from the CLI.

The following syntaxes should be equal:
* CLI:   ```-V margin={left:1cm, right:1cm, bottom:1cm, top:1cm, x:0cm, y:0cm}```
* `defaults.yaml`:

  ```yaml
  variables:
    margin:
      left: 1cm
      right: 1cm
      bottom: 1cm
      top: 1cm
      x: 0cm
      y: 0cm
  ```

Tested on latest release (3.5).
