### ISSUE TITLE
Wrong maxwidth default (HTML output) in Manual

### ISSUE THREAD

**Issue by Wolf-SO** [jgm/pandoc#10683]
I'm using Pandoc version 3.6.3 (on Windows 11, 64 bit) to transform Markdown files into standalone HTML pages. I let Pandoc deduce the formats from the file extensions, my command line is like this:
```
pandoc source.md -o dest.html -s
```
The CSS style (reduced to the `body` section) I find embedded is the generated HTML file is like this:

```css
    body {
      margin: 0 auto;
      max-width: 36em;
      padding-left: 50px;
      padding-right: 50px;
      padding-top: 50px;
      padding-bottom: 50px;
      hyphens: auto;
      overflow-wrap: break-word;
      text-rendering: optimizeLegibility;
      font-kerning: normal;
    }
```
However, in the Manual, section [Variables for HTML](https://pandoc.org/MANUAL.html#variables-for-html "Pandoc - Pandoc User’s Guide") tells us the following:

> *`maxwidth`*
    sets the CSS max-width property (default is 32em). 

Since I found this comment by you @jgm in the [issue #8577](https://github.com/jgm/pandoc/issues/8577#issuecomment-1402239097),

```markdown
  * HTML template:

    + Remove default font size, line height and font family in
      default inline css (#8423). `mainfont`, `fontsize`,
      and `linestretch` can still be used as before; the only difference
      is that we no longer provide opinionated defaults.
      This commit also adds a `maxwidth` variable that sets `max-width`;
      if not set, 36em is used as a default.
```

So maybe we have it right in the version-3.0 changelog but wrong in the online manual.
