### ISSUE TITLE
CredIT Taxonomy "Writing - Review & Editing" is written in JATS output as raw text instead of HTML entity "&amp;"

### ISSUE THREAD

**Issue by Tiago-Manzato** [jgm/pandoc#10744]
** The problem.**
```
---
author:
  - surname: Tal
    given-names: Fulano
    non-dropping-particle: de
    prefix: 'Don'
    suffix: 'IV'
    orcid: 0001-2345-6789-0124
    lattes: 1234567891011123
    equal-contrib: yes
    cor-id: 1
    roles:
      - credit: conceptualization
      - credit: data-curation
      - credit: formal-analysis
      - credit: funding-acquisition
      - credit: investigation
      - credit: methodology
      - credit: project-administration
      - credit: resources
      - credit: software
      - credit: supervision
      - credit: validation
      - credit: visualization
      - credit: writing-original-draft
      - credit: writing-review-editing
    email: fulano@email.com
    affiliation: 
      - id: 1
        label: ^1^
...
```

The YAML Metadata above (used through command: pandoc -f docx -t jats_publishing --wrap=none --metadata-file=article.yaml --bibliography=references.bib -L citation_parser_v1.lua > ..\filters\logs\citation_parser_v1_log.md -s -o article.xml article.docx) produces JATS frontmatter output as below:

```
<contrib contrib-type="author" corresp="yes" equal-contrib="yes">
  <contrib-id contrib-id-type="orcid">0001-2345-6789-0124</contrib-id>
  <contrib-id contrib-id-type="lattes">1234567891011123</contrib-id>
  <name>
    <surname>de Tal</surname>
    <given-names>Fulano</given-names>
    <prefix>Don</prefix>
    <suffix>IV</suffix>
  </name>
  <xref ref-type="corresp" rid="c1">
    <sup>*</sup>
  </xref>
  <role content-type="https://credit.niso.org/contributor-roles/conceptualization/">
    Conceptualization
  </role>
  <role content-type="https://credit.niso.org/contributor-roles/data-curation/">
    Data curation
  </role>
  <role content-type="https://credit.niso.org/contributor-roles/formal-analysis/">
    Formal analysis
  </role>
  <role content-type="https://credit.niso.org/contributor-roles/funding-acquisition/">
    Funding acquisition
  </role>
  <role content-type="https://credit.niso.org/contributor-roles/investigation/">
    Investigation
  </role>
  <role content-type="https://credit.niso.org/contributor-roles/methodology/">
    Methodology
  </role>
  <role content-type="https://credit.niso.org/contributor-roles/project-administration/">
    Project administration
  </role>
  <role content-type="https://credit.niso.org/contributor-roles/resources/">
    Resources
  </role>
  <role content-type="https://credit.niso.org/contributor-roles/software/">
    Software
  </role>
  <role content-type="https://credit.niso.org/contributor-roles/supervision/">
    Supervision
  </role>
  <role content-type="https://credit.niso.org/contributor-roles/validation/">
    Validation
  </role>
  <role content-type="https://credit.niso.org/contributor-roles/visualization/">
    Visualization
  </role>
  <role content-type="https://credit.niso.org/contributor-roles/writing-original-draft/">
    Writing – original draft
  </role>
  <role content-type="https://credit.niso.org/contributor-roles/writing-review-editing/">
    Writing – review & editing
  </role>
  <email>fulano@email.com</email>
  <xref ref-type="aff" rid="aff1">
    <sup>1</sup>
  </xref>
</contrib>
```

Note that the metadata value "label" in "author/affiliation" is in Markdown "^1^" yet it produces the JATS output styled acordingly "`<xref ref-type="aff" rid="aff1"><sup>1</sup></xref>`", but in the case of the CredIT Taxonomy metadata value "- credit: writing-review-editing" it produces the JATS output as "`<role content-type="https://credit.niso.org/contributor-roles/writing-review-editing/">Writing – review & editing</role>`" instead of using the corresponding HTML entity "`&amp;`", which leads to an invalid XML file.

I'm not really sure on how this new CredIT Taxonomy feature works in pandoc but I'm assuming that the text "Writing – review & editing" comes from an online source and is written directly inside the tag <role>, thus, not being treated and converted as Markdown.

**Pandoc version?**
Tests were performed in the latest pandoc version installed on Windows 11 (64-bit)
