### ISSUE TITLE
add list numbering with Greek letters

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#1243]
In some contexts, having the ability to number lists with Greek letters is useful.

```
α. first
β. second
γ. third
δ. four
```

Would it be possible to have this feature for both lowercase and uppercase Greek letters implemented?

Many thanks for your excellent piece of software.

**Comment by pkt** [comment]
FWIW when I implemented the greek number support for LibreOffice I chose στ after ε since this is what is most commonly used in modern greek presentations etc and I haven't seen any complaints yet.

**Comment by ousia** [comment]
> And what would you have come after ε? ϛ or στ or ζ?
> It's already bad enough that HTML uses Greek letters rather than Greek numbers as list markers. I'm not sure about modern Greek usage, but Classicists only ever use the latter, never the former IME.

@bpj, sorry for the long delayed reply.

I asked about letters, because this is a convention when ordering lists. Or at least is what the W3C implemented in the CSS 2.1 specification

Classicists don’t use Greek numerals to number books. Samples are book numbers in  the _Iliad and_ the _Odyssey_ from Homer, the _Republic_ from Plato, and the _Physics_ from Aristotle (to name few).

I think this is similar to mix the Latin letters with Roman numerals. And I guess the W3C thought that decimal were fine instead of Greek numerals.

@pkt list numbering in `pandoc` seems to be based on CSS. The [`list-style-type`]() attribute only allows a limited set of values. There are both alphabetic systems and numbering systems.

`decimal`, `decimal-leading-zero`, `lower-roman` and `upper-roman` are numbering systems. But `lower-greek`, `lower-latin` and `upper-latin` are alphabetic systems.

Numbering text sections and lists using the Greek alphabet is a long established typographic convention in Western books (before the computers were used to typeset them).

**Comment by bpj** [comment]
@ousia I thought I had answered already but apparently not.  

I have an historical Greek grammar which uses (lower case) Greek numbers for list markers, albeit only at a lower level when 'Arabic' numerals, upper case Roman numerals, lower case Latin letters and lower case Roman numbers are already used for higher levels.

As a curiosity I have an Odyssey printed at Uppsala towards the end of the 18th century with a parallel Latin translation.  The Books are designated by Greek letters Α-Ω while the running headers read "Lib. II. ΟΔΥΣΣΕΙΑΣ Β." etc. Every fifth line has an 'Arabic' numeral in the margin.  It used to be the practice to refer to the songs of the Homeric epics by letters of the Greek alphabet, upper and lower case respectively. When you saw e.g. "α 134" you knew what it meant.

**Comment by ousia** [comment]
@bpj, sorry for my belated reply.

Greek lowercase letters have been a way of numbering book sections also in 20th century (such as upper case Roman numerals or Latin letters).

To name the title that comes right now to my mind: _Wahrheit und Methode_ by Hans-Georg Gadamer (the German original edition) uses Greek letters to number its lowest-level sections.

Lower case Greek letters are used in Homer to refer to the books of _The Odyssey_ and upper case letters are used for _The Iliad_.

Upper case letters are also used to refer to books from Plato and Aristotle (although there is an exception with _Metaphysics_, α, which is the second book [and Α, Β and Γ being the first, third and fourth books, respectively]).

I thought it would be fine to be able to create lists numbered with Greek lowercase letters. But @jgm should decide whether this feature is to be included in pandoc (and Markdown) or not.

**Comment by bpj** [comment]
@ousia I found a workaround which which works for HTML/CSS:

1.  Wrap the list which should be marked with a style not supported by Pandoc in a div with an arbitrary distinctive class:

    ```markdown
    <div class="list-marker-milesian">
    1.  Ἑκατομβαιών
    2.  Μεταγειτνιών
    3.  Βοηδρομιών
    4.  Πυανεψιών
    5.  Μαιμακτηριών
    6.  Ποσειδεών
    7.  Γαμηλιών
    8.  Ἀνθεστηριών
    9.  Ἑλαφηβολιών
    10. Μουνιχιών
    11. Θαργηλιών
    12. Σκιροφοριών
    </div>
    ```

2.  Write a CSS file with rules like the one below and include it with the `--css=FILE` option:

    ```css
     /******************************************************************
      ******************************************************************
      ** HOW TO OVERRIDE PANDOC'S HARD-CODED list-style-type for <ol> **
      ******************************************************************
      ******************************************************************/

    /* OPTIONAL FIRST STEP: define a custom list-style-type */

    @counter-style milesian {

        /* A little different from the predefined 'greek', *
         * and unlike that it already works in Firefox!    */

        system: additive;
        range: 1 999;
        additive-symbols: 900 '\3E1', 800 '\3C9', 700 '\3C8', 600 '\3C7', 500 '\3C6', 400 '\3C5', 300 '\3C4', 200 '\3C3', 100 '\3C1', 90 '\3DF', 80 '\3C0', 70 '\3BF', 60 '\3BE', 50 '\3BD', 40 '\3BC', 30 '\3BB', 20 '\3BA', 10 '\3B9', 9 '\3B8', 8 '\3B7', 7 '\3B6', 6 '\3DB', 5 '\3B5', 4 '\3B4', 3 '\3B3', 2 '\3B2', 1 '\3B1';
        /* additive-symbols: 900 'ϡ', 800 'ω', 700 'ψ', 600 'χ', 500 'φ', 400 'υ', 300 'τ', 200 'σ', 100 'ρ', 90 'ϟ', 80 'π', 70 'ο', 60 'ξ', 50 'ν', 40 'μ', 30 'λ', 20 'κ', 10 'ι', 9 'θ', 8 'η', 7 'ζ', 6 'ϛ', 5 'ε', 4 'δ', 3 'γ', 2 'β', 1 'α'; */
        /* The difference:  6 '\3DB', 6 'ϛ', instead of  6 '\3C3\3C4', 6 'στ', */
    }

    /********************************************************
     ** THIS IS THE IMPORTANT BIT FOR OVERRIDING PANDOC:   **
     ** select the ol by its parent and _style attribute_. **
     ** The !important is also *very* important! (sic!)    **
     ** The list-style-type *can* be a predefined one!     **
     ********************************************************/

    div.list-marker-milesian ol[style] { list-style-type: milesian !important }
    ```

The 'magic' is the `[style]` attribute selector and the `!important`; they cause the hard-coded style attribute which Pandoc inserts to be overridden.

The image shows how the effect is limited to the list inside the div with the class.

Of course the rendering engine has to be modern enough to support these features.

References:

*   <www.w3.org/TR/css3-lists/>
*   <http://www.w3.org/TR/css-counter-styles-3/>
*   <http://www.w3.org/TR/predefined-counter-styles/>
*   <https://css-tricks.com/override-inline-styles-with-css/>

I've also been looking at a workaround for LaTeX, but *enumitem* is a tricky beast!
![greek-list-markers-pandoc](https://cloud.githubusercontent.com/assets/1161043/9703694/aa12e4b0-548b-11e5-9615-c1de8c1c2778.png)
