### ISSUE TITLE
pandoc cannot handle \nocite{*} command (LaTeX+Bibliography)

### ISSUE THREAD

**Issue by pprw** [jgm/pandoc#1253]
In the example below, pandoc produces an empty html file when using `\nocite{*}` command. Pandoc works fine with the `\(auto)cite{key}` command.

```
 pandoc test.tex  -o output.html --bibliography mybib.bib 
```

```
% test.tex
\documentclass{article}
\usepackage{biblatex}
\bibliography{mybib}

\begin{document}
%\autocite{author00:_title}
\nocite{*}
\printbibliography
\end{document}
```

```
% mybib.bib
@Book{author00:_title,
  author =   {Author},
  title =    {Title},
  publisher =    {Publisher},
  year =     2000}
```

**Comment by thorade** [comment]
What would I have to put in the markdown metadata? 
I tried (with variants)
```markdown
---
nocite: |
  @*
---
```
but it did not work as expected.

**Comment by jgm** [comment]
If you're targeting latex/pdf, then you can either use
pandoc's native citations system (pandoc-citeproc, which
uses CSL stylesheets) or just tell pandoc to output
natbib or biblatex primitives.  If you want the latter,
do `--natbib` or `--biblatex` when generating latex,
and run pdflatex/biber/bibtex yourself on the result.
If you do it this way, you can simply insert raw `\nocite`
commands into your Markdown source.

If you want to use pandoc-citeproc, then you'll need to
specify individual citations under `nocite`; wildcards
aren't supported at this time, but might be a plausible
feature to add!

+++ Matthis Thorade [May 04 15 03:55 ]:

**Comment by thorade** [comment]
OK, thanks, that helps for now.
What I was looking for was nocite wildcards in markdown, but as you say these are not supported yet, I'll just work around that for now.

**Comment by nkalvi** [comment]
@jgm 
Would this work with references given in meta data block of the markdown source too? F.ex. will this work? (When run with `pandoc --filter pandoc-citeproc t.txt  -s -t latex`)

```
---
references:
- type: article-journal
  id: WatsonCrick1953
  author:
  - family: Watson
    given: J. D.
  title: 'Molecular structure of nucleic acids: a structure for deoxyribose
    nucleic acid'
  title-short: Molecular structure of nucleic acids
  container-title: Nature
  volume: 171
  issue: 4356
  page: 737-738
  DOI: 10.1038/171737a0
  language: en-GB
  
...

Testing nocite command

\nocite{*}
```
