### ISSUE TITLE
Duplicate IDs for font in epub content.opf

### ISSUE THREAD

**Issue by danmichaelson** [jgm/pandoc#1254]
When a CSS stylesheet specifies multiple formats for a font, Pandoc makes multiple entries in content.opf, all with the same ID. I'm not sure what the solution is or if it's allowed to have multiple formats for a font in epub; but if it is allowed, I'm sure they shouldn't have duplicate ID's in the content.opf XML. It prevents the epub from validating on submission to iBooks Store.

CSS:

``` css
@font-face {
  font-family: 'regular';
  src: url('tradegothicltstd-light-webfont.eot');
  src: url('tradegothicltstd-light-webfont.eot?#iefix') format('embedded-opentype'),
  url('tradegothicltstd-light-webfont.woff') format('woff'),
  url('tradegothicltstd-light-webfont.ttf') format('truetype');
  font-weight: normal;
  font-style: normal;
}
```

content.opf:

``` xml
    <item id="tradegothicltstd-light-webfont" href="tradegothicltstd-light-webfont.woff" media-type="application/x-font-woff" />
    <item id="tradegothicltstd-light-webfont" href="tradegothicltstd-light-webfont.ttf" media-type="application/x-font-truetype" />
    <item id="tradegothicltstd-light-webfont" href="tradegothicltstd-light-webfont.eot" media-type="application/vnd.ms-fontobject" />
```

I'm using edge version of Pandoc from Git (to take advantage of the <video> tag feature); this could be a recent regression because I don't recall this happening in production version?
