### ISSUE TITLE
No title page in epub output

### ISSUE THREAD

**Issue by johngrasty** [jgm/pandoc#1744]
Here is the YAML (edited for privacy):

```

---
title:
- type: main
  text: Title of the Book
- type: subtitle
  text: A subtitle of the book
creator:
- role: author
  text: Name of Author
publisher:  Publisher Name
rights:  (c) 2002 Author Name, All rights reserved. No part of this publication may be reproduced without permission in writing from the publisher, except in the case of brief quotations embodied in critical articles or reviews.
...
```

I get no title page in the resulting epub (or in the mobi file after using `kindlegen`).

I do get a simple title/author title page when using this YAML block:

```

---
title: Title of Book
author: Name of Author
publisher:  Name of Publisher
rights:  (c) 2002 Name of Author, All rights reserved. No part of this publication may be reproduced without permission in writing from the publisher, except in the case of brief quotations embodied in critical articles or reviews.
...
```

Does the automatic title page only get generated with the simpler YAML on purpose? Thanks!
