### ISSUE TITLE
Citation - footnote collision

### ISSUE THREAD

**Issue by tomduck** [jgm/pandoc#2083]
Placing a footnote after a citation results in unexpected output.

For example, suppose I have the following in demo.md

    Source materials include @fenner2012a[^1] and class notes.

    [^1]: Subscription required.

and process it with

    $ pandoc demo.md --from=markdown+citations --filter pandoc-citeproc -o demo.pdf

The result in the pdf looks like

    Source materials include Fenner (2012 ˆ1) and class notes.

    Fenner, Martin. 2012. “One-Click Science Marketing.” Nature Materials 11 (4).
    Nature Publishing Group: 261–63. doi:10.1038/nmat3283.

Notice that there is no footnote, and `^1` appears in the citation.  Putting a space between the citation and the footnote gives the same result.

The full `demo.md` for my test is as follows:

```
Source materials include @fenner2012a[^1] and class notes.

[^1]: Subscription required.

---
references:
- id: fenner2012a
  title: One-click science marketing
  author:
  - family: Fenner
    given: Martin
  container-title: Nature Materials
  volume: 11
  URL: 'http://dx.doi.org/10.1038/nmat3283'
  DOI: 10.1038/nmat3283
  issue: 4
  publisher: Nature Publishing Group
  page: 261-263
  type: article-journal
  issued:
    year: 2012
    month: 3
...
```
