### ISSUE TITLE
allow multiple publishers

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#2143]
@jgm, would it be possible that the YAML `publisher` field allows multiple publishers?

This would be an important feature for jointly published works.

**Comment by nickbart1980** [comment]
No, this could only be done properly if the CSL specs were updated to support this.

We'd need support for multiple places, too, something like

```
  publisher: 
  - name: Hackett
    place:
    - Indianapolis
      Cambridge
  - name: Routledge
    place:
    - London
      New York
```

It'd be a good idea to bring this up on the xbiblio mailing list.

BTW, there are other similar issues: support for multiple reviewed works, e.g., is missing, too.
