### ISSUE TITLE
iframes not being rendered correctly

### ISSUE THREAD

**Issue by damienh** [jgm/pandoc#2244]
We are using Pandoc in our jekyll site and it appears that iframes are being escaped illustrated below.

![screen shot 2015-06-24 at 15 02 09](https://cloud.githubusercontent.com/assets/810107/8358297/606806a0-1b57-11e5-9f77-f3d7738b0aca.png)

Here is our config file where we use pandoc to convert markdown to html

```
gems: [ 'jekyll-pandoc-multiple-formats' ]
pandoc:
  output: ./tmp
  flags: '--parse-raw --smart --section-divs'
  outputs:
    markdown: redcarpet
```

here is the iframe in our markdown file

```
<div class="scratch-preview">
	<iframe allowtransparency="true" width="485" height="402" src="http://scratch.mit.edu/projects/embed/26818098/?autostart=false" frameborder="0"></iframe>
	<img src="space-final.png">
</div>
```

If anyone can point me in the right direction it would be very much appreciated.
