### ISSUE TITLE
Chapter number template variable for EPUB

### ISSUE THREAD

**Issue by gohai** [jgm/pandoc#2296]
We'd love to be able to create CSS rules that only apply to a single chapter of a book. For this, having a template variable that contains the current chapter's number or title would be very helpful, since we could use it to set e.g. the body element's id.

We haven't found any other way to achieve this. Section elements have the title as their id attribute, but there are often multiple sections in a chapter, and not necessarily all nested. I looked into trying this myself in EPUB.hs, but found that it doesn't already use defField and friends, so implementing this is slightly above my command of Haskell unfortunately. I'd be great if this could be considered however. Thanks!

**Comment by ousia** [comment]
@gohai, I’m not sure I understand your question.

I do apply rules to single chapters in ePub documents, such as in:

``` markdown
# My Special Chapter {.special-chapter}

Text in special chapter
```

Since `--section-divs` is mandatory in ePub conversion (it is a reasonable measure), I think you can format it with the following code:

``` css
.special-chapter {
    font: Calibri, sans-serif;
    }

.special-chapter > h1 {
    margin-right: 10%;
    text-align: right;
}

.special-chapter > h1 {
    margin-right: 10%;
    text-align: right;
}

.special-chapter > p {
    text-indent: 5%;
    line-height: 130%;
    font-size: normal;
}

.special-chapter > h1 + .special-chapter > p {
    text-indent: 0%;
}
```

I think that with a class attribute you can style the concrete chapter in ePub.

Or have I missed something?

BTW, if not all sections in a chapter are nested (in the ePub file or invoking `--section-divs`), this is a bug.
