### ISSUE TITLE
The variable “polyglossia-otherlangs” should have fields

### ISSUE THREAD

**Issue by nickbart1980** [jgm/pandoc#2437]
Currently, no variants can be set for polyglossia’s secondary languages.

I’d suggest that the variable `polyglossia-otherlangs` should have the fields `.name` and `.variant`, and multiple `\setotherlanguage{}` commands rather than one `\setotherlanguages{}` command should be used.

Accordingly, the `default.latex` template should contain:  

~~~
$for(polyglossia-otherlangs)$
\setotherlanguage
$if(polyglossia-otherlangs.variant)$[variant=$polyglossia-otherlangs.variant$]$endif$
{$polyglossia-otherlangs.name$}
$endfor$
~~~

**Alternative: `.options` fields**

Use `polyglossia-mainlang` and `polyglossia-otherlangs` variables, both having `.name` and `.options` fields, where `.options` can have a value of `variant=…`, e.g., `variant=british`.

An `.options` field would make it easier to deal with other polyglossia options, too, e.g.,

`ar-TN` => `\setotherlanguage[locale=tunisia]{arabic}`

`de-AT-1901` => `\setotherlanguage[variant=austrian, spelling=old]{german}`

**Comment by jgm** [comment]
@mb21 can you comment?  This seems reasonable to me. The LaTeX writer would need to be changed to set these variables differently.

**Comment by mb21** [comment]
Agreed, the otherlangs variable didn't get the proper treatment in the language -> lang change. But then why not make it consistent (@nickbart's alternative), in YAML:

    babel-lang: arabic
    polyglossia-lang:
      name: arabic
      variant: whatever
      locale: tunisia
    polyglossia-otherlangs:
      - name: german
        variant: austrian
      - name: chinese
        variant: ""

This makes the `polyglossia-lang` variable a bit more complex (it's a dictionary now) but offers more flexibility.

**Comment by nickbart1980** [comment]
… or simpler, since most likely we’ll never be needing the individual components:

```yaml
babel-lang: arabic
polyglossia-lang:
  name: arabic
  options: variant=whatever, locale=tunisia
polyglossia-otherlangs:
  - name: german
    options: variant=austrian
  - name: chinese
    options: variant=whatever
```
