### ISSUE TITLE
Feature Request: Case sensitive YAML variables

### ISSUE THREAD

**Issue by DaveJarvis** [jgm/pandoc#2517]
# Overview

Consider:

```yaml
entity:
  name:
    singular: bacterium
    plural: bacteria
  capname:
    singular: Bacterium
    plural: Bacteria
```

The extra level of indirection could be eliminated by supporting case sensitivity:

```yaml
entity:
  singular: bacterium
  plural: bacteria
  Singular: Bacterium
  Plural: Bacteria
```

# Use Case

The end user would have to enable case-sensitive YAML variables from the command-line, explicitly (to maintain backwards compatibility), such as:

    pandoc filename.md --template filename.yaml --case-sensitive

# Request

I would like to request the ability for pandoc to substitute YAML variables in a case-sensitive fashion.

# Tangent

Pre-parsing could eliminate all duplication, which is beyond the scope of this feature request. For example (pardon the syntax):

```yaml
entity:
  singular: bacterium
  plural: bacteria
  Singular: %%init_cap( $entity.name.singular$ )%%
  Plural: %%init_cap( $entity.name.plural$ )%%
```

Arguably, changing the case could reside in the markdown (e.g., using pander), but it feels cleaner to have it in the YAML, which frees the markdown from dependencies.

**Comment by jgm** [comment]
Why not
```
entity:
  singular:
    lowercase: bacterium
    uppercase: Bacterium
```

**Comment by DaveJarvis** [comment]
Using `uppercase` vs `lowercase` still requires three tiers instead of two. The naming isn't important. For example:

```yaml
entity:
  lc:
    singular: bacterium
    plural: bacteria
  uc:
    singular: Bacterium
    plural: Bacteria
```

```yaml
entity:
  singular:
    lowercase: bacterium
    uppercase: Bacterium
  plural:
    lowercase: bacteria
    uppercase: Bacteria
```

Those are, for all intents, equivalent (admittedly, the latter has a nicer alignment). What I'd like to do is eliminate the extra level altogether:

```yaml
entity:
  single: bacterium
  plural: bacteria
  Single: Bacterium
  Plural: Bacteria
```

Variable case sensitivity would be useful for screenplays as well, where the first instance of a character's name is typically all uppercase:

```yaml
name:
  first: Jean-Luc
  FIRST: JEAN-LUC
```

**Comment by jgm** [comment]
I can see the use of this, but as a change here would break
backwards compatibility, I think we'd need a more compelling
reason to make it.  There might be many existing documents
that use 'Title:' in metadata, and they'd all break with
this change.

Note that if you want two levels, you could always use
`author` and `authorcaps` or something like that.

+++ Dave Jarvis [Nov 12 15 14:37 ]:

**Comment by DaveJarvis** [comment]
> There might be many existing documents that use 'Title:' in metadata, and they'd all break with this change.

Even if sensitivity was only enabled, explicitly, using a very specific command-line parameter?

> I think we'd need a more compelling reason to make it.

Several specifications respect case of YAML keys:

* YAML and JSON should have [interoperability](http://jsontoyaml.com/), and JSON is case-sensitive
* [RAML](http://docs.raml.org/specs/1.0/#raml-10-spec-markup-language), an application of the YAML 1.2 specification, is case-sensitive.
* The Ruby YAML parser is case-sensitive, as are several Go YAML parsers.
* [Swagger](http://swagger.io/specification/) is case-sensitive.
* Various [tools](https://github.com/dbohdan/remarshal) convert between TOML, YAML, and JSON.

There is a large tooling infrastructure that can be leveraged and a world of pipelines that are possible when the option of treating YAML case-sensitively exists. How many people would take advantage of such interoperability within their MD text is unknown, but likely rather small.

**Comment by jgm** [comment]
+++ Dave Jarvis [Nov 12 15 22:36 ]:
>     There might be many existing documents that use 'Title:' in
>     metadata, and they'd all break with this change.
>
>   Even if sensitivity was only enabled, explicitly, using a very specific
>   command-line parameter?
>
>     I think we'd need a more compelling reason to make it.
>
>   Several specifications respect case of YAML keys:
>     * YAML and JSON should have [1]interoperability, and JSON is
>       case-sensitive
>     * [2]RAML, an application of the YAML 1.2 specification, is
>       case-sensitive.
>     * The Ruby YAML parser is case-sensitive, as are several Go YAML
>       parsers.
>     * [3]Swagger is case-sensitive.
>     * Various [4]tools convert between TOML, YAML, and JSON.
>
>   There is a large tooling infrastructure that can be leveraged and a
>   world of pipelines that are possible when the option of treating YAML
>   case-sensitively exists. How many people would take advantage of such
>   interoperability within their MD text is unknown, but likely rather
>   small.

Changes that involve breaking backwards compatibility should
be discussed on pandoc-discuss, so I suggest you post there
and see what people say.

I'm a bit reluctant to add the behavior under a command-line
option.

**Comment by jgm** [comment]
As far as I can see, case-sensitive YAML metadata fields already work in pandoc.  No?

**Comment by DaveJarvis** [comment]
Months ago, it appears I managed to stumble on the *only* case (pardon the pun) that doesn't work: `title`. For example:

```yaml
character:
  protagonist:
    title: roboticist
    Title: Roboticist
```

In the text, both `$character.protagonist.title$` and `$character.protagonist.Title$` get resolved to the same value. I incorrectly believed, months ago, that pandoc, therefore, treated YAML case insensitively.

Treating the key `title` case insensitively, in my opinion, violates the principle of least astonishment. I understand that it is necessary, though.

I'd be tempted to treat it as a bug because `title` and `character.protagonist.title` are in two different namespaces.
