### ISSUE TITLE
Feature Request: distinguish numbered lists and example lists in HTML

### ISSUE THREAD

**Issue by klapheke** [jgm/pandoc#2524]
As of the fixing of #1902, there is no way to distinguish example numbering in HTML output from ordinary numbered lists. It would be nice to have something like `class="example"` on the former so that these can be styled differently.

I understand I can just wrap the example lists in `<div>` blocks (#2408), but this seems like a natural addition given that pandoc's syntax treats the two list types as categorically different.

**Comment by adamiturabi** [comment]
@alexklapheke Were you able to style the example list with parentheses, like `(1)`? I'm not very good with CSS but it seems like a separate counter is needed which messes with the start value.

**Comment by alexklapheke** [comment]
I've never tried, but I think something like this should work:

```css
body { /* Or section.level1, etc. */
    counter-reset: example;
}
ol.example > li {
    list-style: none;
    counter-increment: example;
}
ol.example > li::marker {
    content: "(" counter(example) ") ";
}
```
