### ISSUE TITLE
Errorneous escaping of *fontoptions YAML metadata

### ISSUE THREAD

**Issue by istefani** [jgm/pandoc#2565]
Example:
```yaml
mainfont: Gentium Book Basic
mainfontoptions:
 - SmallCapsFont={Gentium Plus}, SmallCapsFeatures={Letters=SmallCaps}
```

Results in:
```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "kernel/misplaced-equals-sign"
! 
! Misplaced equals sign in key-value input 17
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................  
                                                  
l.17 ...\{Letters=SmallCaps\}]{Gentium Book Basic}
```
