### ISSUE TITLE
Images in stylesheets not embedded in epub

### ISSUE THREAD

**Issue by yihui** [jgm/pandoc#2733]
The full minimal reproducible example can be downloaded here: https://www.dropbox.com/sh/v53cqqr854tdf5b/AAAGpUYy0MljfHaT9FhOyGENa?dl=0

test.md

``` md

---
title: Test
author: John Smith
stylesheet: test.css

---

Test

<div class="caution">Test block.</div>
```

test.css

``` css
.caution {
  padding: 1em 1em 1em 4em;
  margin-bottom: 10px;
  background: #f5f5f5 url("images/caution.png") left center/3em no-repeat;
}
```

images/caution.png

![caution](https://cloud.githubusercontent.com/assets/163582/13208599/2ce94b12-d8e0-11e5-9b9a-76d975e3c952.png)

To reproduce the problem:

``` bash
pandoc -o test.epub test.md
```

The caution icon is missing in the block when we view test.epub:

![screen shot 2016-02-21 at 9 16 19 pm](https://cloud.githubusercontent.com/assets/163582/13208633/6d424c72-d8e0-11e5-81ed-ce2309aaaa39.png)

If we use the developer tools in calibre, we can see the image images/caution.png is not found. I think Pandoc should be able to recognize the external resources in the stylesheet, and copy them when rendering epub.
