### ISSUE TITLE
Bibliography not shown?

### ISSUE THREAD

**Issue by matthiasbeyer** [jgm/pandoc#2795]
Hi,

I have

```tex
$if(biblatex)$                                                                                                                                                                                                    
    \printbibliography$if(biblio-title)$[title=$biblio-title$]$endif$                                                                                                                                             
$endif$
```

in my template.

I have

```yaml
references:
- id: examplebibentry
  type: no-type
  author:
  - family: example
  issued:
  - year: '1970'
    month: '01'
  title: example
  URL: http://example.com
```

In my header and 

```bibtex
@misc{examplebibentry,
    author = "example",
    title = "example",
    month = "01",
    year = {1970},
    url = {http://example.com},
}
```

in a bibtex file I pass with `--bibliography <file>`. I have 

```
 Examples

Here go some \Gls{Example}, so we can see what this compiles to. This example is
taken from [see @examplebibentry, page 15 ff.].
```

In my sources.

Though I'm not getting any bibliography in my output paper.

---

https://github.com/matthiasbeyer/pandoc-paper-template/tree/bibtex-support

Here are my sources. The `default.nix` should fetch all dependencies... If you use Nix as package manager.
