### ISSUE TITLE
Please support ghc-8.0.1

### ISSUE THREAD

**Issue by octoploid** [jgm/pandoc#2938]
There are a number of arbitrary version upper bounds, that have to be lifted:
`data-default`
`haddock-library`
`time`
and cmark-0.5.2 needs adjustments, too.

Once all this is done pandoc actually builds fine with ghc-8.0.1.

**Comment by jgm** [comment]
If you've made the needed changes, built and tested, why not
send a PR?

+++ octoploid [May 22 16 01:31 ]:

**Comment by jgm** [comment]
I've uploaded cmark-0.5.2.1 which allows latest base.
Working on pandoc now.

+++ octoploid [May 22 16 01:31 ]:

**Comment by jgm** [comment]
I'm getting stuck on this, which I don't understand:
```
aeson-0.11.2.0: build
Progress: 2/7
--  While building package aeson-0.11.2.0 using:
      /Users/jmacf/.stack/setup-exe-cache/x86_64-osx/setup-Simple-Cabal-1.24.0.0-ghc-8.0.1 --builddir=.stack-work/dist/x86_64-osx/Cabal-1.24.0.0 build --ghc-options " -ddump-hi -ddump-to-file"
    Process exited with code: ExitFailure 1
    Logs have been written to: /Users/jmacf/src/pandoc/.stack-work/logs/aeson-0.11.2.0.log

    Configuring aeson-0.11.2.0...
    Warning: This package indirectly depends on multiple versions of the same
    package. This is highly likely to cause a compile failure.
    package deepseq-1.4.2.0 requires array-0.5.1.1
    package text-1.2.2.1 requires array-0.5.1.1
    package deepseq-1.4.2.0 requires array-0.5.1.1
    package containers-0.5.7.1 requires array-0.5.1.1
    package binary-0.7.5.0 requires array-0.5.1.1
    package attoparsec-0.13.0.2 requires array-0.5.1.1
    package pretty-1.1.3.3 requires deepseq-1.4.2.0
    package vector-0.11.0.0 requires deepseq-1.4.2.0
    package unordered-containers-0.2.7.0 requires deepseq-1.4.2.0
    package time-1.6.0.1 requires deepseq-1.4.2.0
    package text-1.2.2.1 requires deepseq-1.4.2.0
    package tagged-0.8.4 requires deepseq-1.4.2.0
    package scientific-0.3.4.6 requires deepseq-1.4.2.0
    package dlist-0.7.1.2 requires deepseq-1.4.2.0
    package containers-0.5.7.1 requires deepseq-1.4.2.0
    package bytestring-0.10.6.0 requires deepseq-1.4.2.0
    package attoparsec-0.13.0.2 requires deepseq-1.4.2.0
    package aeson-0.11.2.0 requires deepseq-1.4.2.0
    Building aeson-0.11.2.0...
    Preprocessing library aeson-0.11.2.0...
    [ 1 of 16] Compiling Data.Aeson.Functions ( Data/Aeson/Functions.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Data/Aeson/Functions.o )
    [ 2 of 16] Compiling Data.Aeson.Internal.Time ( Data/Aeson/Internal/Time.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Data/Aeson/Internal/Time.o )
    [ 3 of 16] Compiling Data.Aeson.Types.Internal ( Data/Aeson/Types/Internal.hs, .stack-work/dist/x86_64-osx/Cabal-1.24.0.0/build/Data/Aeson/Types/Internal.o )
    
    /private/var/folders/hn/z9_tw0y54358075qvw479qfc2qx5bb/T/stack67125/aeson-0.11.2.0/Data/Aeson/Types/Internal.hs:345:17: error:
        • No instance for (Semigroup Builder)
            arising from the 'deriving' clause of a data type declaration
          Possible fix:
            use a standalone 'deriving instance' declaration,
              so you can specify the instance context yourself
        • When deriving the instance for (Semigroup Encoding)
```
This is with the following stack.yaml:
```
flags:
  pandoc:
    trypandoc: false
    https: true
    embed_data_files: false
    old-locale: false
    network-uri: true
packages:
- '.'
- '../cmark-hs'
resolver: nightly-2016-05-21
compiler: ghc-8.0.1
setup-info:
 ghc:
  macosx:
   8.0.1:
    url: https://downloads.haskell.org/~ghc/8.0.1/ghc-8.0.1-x86_64-apple-darwin.tar.xz
    content-length: 118496652
    sha1: e7a1c558a095afbc4fb514256be940ddb0f23a29
extra-deps:
- haddock-library-1.4.1
- texmath-0.8.6.2
 #- cmark-0.5.2.1
- time-1.6.0.1
- data-default-0.7.0
- data-default-class-0.1.0
- data-default-instances-base-0.1.0
- array-0.5.1.1
- containers-0.5.7.1
- deepseq-1.4.2.0
- directory-1.2.6.3
- filepath-1.4.1.0
- process-1.4.2.0
- transformers-0.5.2.0
- transformers-compat-0.5.1.4
- unix-2.7.2.0
```
and the latest cmark-hs source in ../cmark-hs.
Any ideas?  You said you got it to build?
