### ISSUE TITLE
pandoc-citeproc: IEEE.cls swallowing multiple sequential citations, different from built-in style.

### ISSUE THREAD

**Issue by jeeger** [jgm/pandoc#3598]
Using the IEEE.cls file from https://www.zotero.org/styles/ieee, multiple citations are swallowed by citeproc silently. Using the built-in style, multiple citations are typeset correctly. 

If this is WAD, would it be possible for pandoc to issue a warning about citations being dropped due to the citations being in the wrong format? The current behavior is a bit confusing, seeing as the built-in citation style works differently.

Test with `pandoc --filter pandoc-citeproc -t html -f markdown+link_attributes test.md -s -o test.html` and `pandoc --filter pandoc-citeproc -t html --csl IEEE.csl -f markdown+link_attributes test.md -s -o test.html`. 

Expected: "when citing [1 2]"
Actual: "when citing [1]"

MWE:

```
---
references:
- type: article-journal
  id: citation1
  author:
  - family: Watson
    given: J. D.
  - family: Crick
    given: F. H. C.
  issued:
    date-parts:
    - - 1953
      - 4
      - 25
  title: 'Molecular structure of nucleic acids: a structure for deoxyribose
    nucleic acid'
  title-short: Molecular structure of nucleic acids
  container-title: Nature
  volume: 171
  issue: 4356
  page: 737-738
  DOI: 10.1038/171737a0
  URL: http://www.nature.com/nature/journal/v171/n4356/abs/171737a0.html
  language: en-GB

- type: article-journal
  id: citation2
  author:
  - family: Watson
    given: J. D.
  - family: Crick
    given: F. H. C.
  issued:
    date-parts:
    - - 1953
      - 4
      - 25
  title: 'Molecular structure of nucleic acids: a structure for deoxyribose
    nucleic acid'
  title-short: Molecular structure of nucleic acids
  container-title: Nature
  volume: 171
  issue: 4356
  page: 737-738
  DOI: 10.1038/171737a0
  URL: http://www.nature.com/nature/journal/v171/n4356/abs/171737a0.html
  language: en-GB
...

I am citing [@citation1] and [@citation2]. However, when citing
[@citation1 @citation2], the latter disappears.

```

Pandoc version: pandoc.exe 1.19.2.1
Compiled with pandoc-types 1.17.0.4, texmath 0.9, skylighting 0.1.1.4
Default user data directory: C:\Users\z003m8fk\AppData\Roaming\pandoc
Copyright (C) 2006-2016 John MacFarlane
Web:  http://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
