### ISSUE TITLE
Pandoc 2.0.3 Beamer compilation fails due to Hyperref clash

### ISSUE THREAD

**Issue by RicherMans** [jgm/pandoc#4100]
Hey there, I used pandoc 1.19 without any problems for beamer generation. Since the new version (2.0.3) however, I get a hyperref clash when I compile.
The following example:
```
---
documentclass: beamer
author:
- Me
output:
    highlight: tango
    beamer_presentation:
        toc: true
---
```

when compiled with `pandoc -s -f markdown tmp.md -t beamer -o my.pdf` results in the following:

```
Error producing PDF.
! LaTeX Error: Option clash for package hyperref.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.26 \hypersetup
```
