### ISSUE TITLE
HTML Syntax Highlighting: CSS Issues With Line-Numbers

### ISSUE THREAD

**Issue by tajmone** [jgm/pandoc#4128]
pandoc 2.0.3

There are a number of CSS issue with the current way pandoc syntax highlights code with line number in HTML (and similar CSS based formats possibly).

I'll explain here the various issue, and provide examples of how I've worked around them in my custom CSS/SCSS stylesheets.

### Line Numbers Background Color

The main issue — at least IMO — has to do with using line numbers when a background color is set for the code block. Line numbers are generated via `div.sourceLine::before` with a negative absolute position, and adding a positive left margin to `pre.numberSource`.

Here is a rough resume of the mentioned CSS in pandoc's default generated CSS:

``` css
pre.numberSource div.sourceLine::before,
.numberSource a.sourceLine::before {
    position: absolute;
    left: -5em;
/* [... other CSS ...] */
}

pre.numberSource {
    margin-left: 3em;
    border-left: 1px solid #bdae9d;
/* [... other CSS ...] */
}
```

This positions the line numbers _outside_ the background color of the source code; and this seems the reason why setting the line numbers background color in custom JSON styles has no effect on their BG color.

In a project of mine, that uses only custom CSS to style pandoc higlighted code, I've worked around this by removing the margin (and border) from `pre.numberSource`, and add it instead to `pre.numberSource div.sourceLine`, so that only the div with the source line is shifted right, leaving the background color where the line numbers will be produced by `div.sourceLine::before`. I also changed the CSS for the line numbers border.

Here are my changes that allow to preserve background color behind line numbers (it's taken from a Sass file, but the point is clear):

``` scss
pre.numberSource {
// *** REMOVED: ***
    // margin-left: 3em;
    // border-left: 1px solid red;
// [... more SCSS, omitted ...]
}
// *** ADDED: *** Needed to preserve Line Numbers background-color
pre.numberSource div.sourceLine {
    margin-left: 4em;  // Space for Line Numbers with 4 digits maximum!
    padding-left: 4px; // Add some space to distance from line numbers
}
// *** LINE-NUMS BORDER: *** The border separating linenums from code
pre.numberSource div.sourceLine::before {
    border-right: 1px solid $LineNumsBorderColor;
}
```

### Empty Lines Height Issue

Also, I've experienced vertical gaps in the line numbers' border when one or more empty lines of code are present. This is due to the lack of actual contents in `div.sourceLine`, which affects the height of the line.

My workaround consists in using `::after` to always add a thin space, so that even empty line will have some content:

``` scss
pre.numberSource div.sourceLine::after {
    content: "\2009"; // Thin space: &thinsp;
}
```

> __NOTE__: The presence of the mentioned gaps will depend largely on the basic CSS of the document. In my case, it showed up in documents that use `normalize.css`, so chances are that the gaps will show up in most cases. Furthermore, this thin space solution shouldn't cause problems in any context.

### Inline Code Issue

The following pandoc default CSS ends up forcing pandoc styles on inline code too:

``` css
pre, code {
    color: #bdae9d;
    background-color: #2a211c;
}
```

IMO, pandoc styles should not affect code tags that weren't highlighted/generated by pandoc. This is safer and less intrusive:

``` scss
// Changed: added the .sourceCode class to avoid interfering with base styles!
pre.sourceCode,
code.sourceCode {
    color: #bdae9d;
    background-color: #2a211c;
}
```

... but I haven't yet tested it agains using pandoc to highlight inline code (I suppose the class names are the same).

**Comment by jgm** [comment]
Try with 2.0.4, please.  See the changelog -- part of the
release was fixing some highlighting issues.

If you still see problems, could you give a small example
and exact command line, so we can reproduce the issue?

**Comment by tajmone** [comment]
Ok, I've updated to v2.0.4. 

I noticed some changes in the CSS, but the problems mentioned above don't seem affected by them, and they still persist.

I'll paste here some shell scripts to demonstrate the problem and possible solution.

### Problem Example

`````````````````````bash
cat << 'EOF' | pandoc -s --highlight-style=zenburn -o problem.html

# Problem Example

<style media="screen" type="text/css">
.sourceLine {
    /* VERTICAL BORDER TO SHOW GAPS */
    border-left: 2px solid red;
}
</style>

``` { .python .numberLines }
# empty line ahead:

print "Hello World!"
```
EOF
`````````````````````

- Linenumbers are still shifted left via negative position values, so they're outside of the background color of the actual code.
- The added custom CSS provided in the example demonstrates that empty lines cause line-height differences (ie: gaps in the red border)

### Solution Example

This variation on the above example fixes the first two problems mentioned:

`````````````````````bash
cat << 'EOF' | pandoc -s --highlight-style=zenburn -o solution.html

# Solution Example

<style media="screen" type="text/css">
    /* VERTICAL BORDER TO SHOW GAPS */
        .sourceLine {
            border-left: 2px solid red;
        }
    /* ===  EMPTY LINES GAP FIX === */
        .sourceLine::after {
            content: "\2009"; /* Thin space */
        }
    /* ===  LINE-NUMBERS BG COLOR FIX === */
        pre.numberSource a.sourceLine::before {
            color: white; /* linenumbers color */
        }
        pre.numberSource a.sourceLine {
            margin-left: 4em;
            padding-left: 4px;
        }
</style>

``` { .python .numberLines }
# empty line ahead:

print "Hello World!"
```
EOF
`````````````````````

**Comment by tajmone** [comment]
I think it's also worth considering pandoc default CSS for overflow:

``` css
.sourceCode { overflow: visible; }
```

IMO, this is not the best setting since it allows code to overflow and spill outside its container. Source code lines are usually quite long, due to monospaced fonts; often they'll be well over 80 characters.

This poses a problem, especially on handheld devices.

### Overflow Problem

This example demonstrated the overflow issue by adding some CSS to restrict body width to 400px:

``````````````````````bash
cat << 'EOF' | pandoc -s --highlight-style=zenburn -o overflow-problem.html

# Overflow Problem

<style media="screen" type="text/css">
    /* BODY WITH TO DEMONSTRATE CODE OVERFLOW */
        body { width: 400px; }
</style>
``` python
# I'm a very long comment and will cause an overflow in my div container, causing this line to spill over the div... 

print "Hello World!"
```
EOF
``````````````````````

### Overflow Solution

And this example demonstrates how a default setting of `.sourceCode { overflow: auto; }` might be a better choice:

``````````````````````bash
cat << 'EOF' | pandoc -s --highlight-style=zenburn -o overflow-solution.html

# Overflow Solution

<style media="screen" type="text/css">
    /* BODY WITH TO DEMONSTRATE CODE OVERFLOW */
        body { width: 400px; }
    /* === CODE OVERFLOW FIX === */
        .sourceCode { overflow: auto; }

</style>
``` python
# I'm a very long comment but I will not cause an overflow in my div container, because of the CSS fix... 

print "Hello World!"
```
EOF
``````````````````````

The problem here is that pandoc built-in styles impose `overflow: visible` on the `.sourceCode` class; this is a very specific definition that will take precedence over most general stylesheets — which usually style the `<pre>` and `<code>` tags, which are less specific than pandoc's CSS targetting the classname.

What are the reasons behind the `visible` setting choice?
