### ISSUE TITLE
"institute" metadata doesn't do anything

### ISSUE THREAD

**Issue by louisabraham** [jgm/pandoc#4209]
I tried to compile the following document

```markdown
---
title: test
institute: institute
---
```

But the `institute` field just doesn't work.

I checked my default.latex, and it contains
```latex
$if(institute)$
\providecommand{\institute}[1]{}
\institute{$for(institute)$$institute$$sep$ \and $endfor$}
$endif$
```

I tried several variants, but it just doesn't work.

**Comment by jgm** [comment]
You need to be using a documentclass that defines the
`\institute` macro, or define your own.

+++ louisabraham [Dec 28 17 10:35 ]:

**Comment by GandalfSaxe** [comment]
For referece, this could for example add this to your yaml file:

header-includes: |
  \providecommand{\institute}[1]{
    \postauthor{\end{tabular}\\[0.5cm]\textit{#1}\end{center}}
  }

**Comment by mguijarr** [comment]
Hi, I am writing a scientific paper with pandoc, with pdf output. I need to add the institute. So, following the example provided by @GandalfSaxe I added this to the yaml part of my .md source file:

```yaml
---
title: the title ok
author:
  - author1 ok
  - author2 ok
date: 2019-09-24
abstract: |
    the abstract ok
header-includes: |
    \providecommand{\institute}[1]{
    \postauthor{\end{tabular}\[0.5cm]\textit{#1}\end{center}}
    }
---
```

Unfortunately, with `header-includes` I have the following error:

    Error producing PDF.
    ! LaTeX Error: Missing \begin{document}.

If I remove the `header-includes` section it works fine - but I have no institute :cry: 

What should I do ?
