### ISSUE TITLE
YAML metadata title using causes error in EPUP generation

### ISSUE THREAD

**Issue by ricardodelagarza** [jgm/pandoc#4486]
When use YAML format metadata  in .MD document as suggested:
```
---
title:
- type: main
  text: My Book
- type: subtitle
  text: An investigation of metadata
```

Bring the following error:
```
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
```

In previous versions it worked fine. The current work around is use simple title like:
```
---
title:  My Book 
```
Although you may not use the [documented alternatives](https://pandoc.org/MANUAL.html#epub-metadata):
Title
Either a string value, or an object with fields `file-as` and type, or a list of such objects. Valid values for type are `main`, `subtitle`, `short`, `collection`,` edition`, `extended`.
