### ISSUE TITLE
better CSS code for a.footnote-ref in ePub

### ISSUE THREAD

**Issue by ousia** [jgm/pandoc#4487]
The current CSS code for footnote references in ePub reads:

``` css
 a.footnote-ref { vertical-align: super; }
```
This may lead to extra space in line height (as shown in the second paragraph of the following screenshot):

![both-options](https://user-images.githubusercontent.com/203767/37726191-14c1a344-2d35-11e8-83dd-170ca71fc2a9.png)

A way to avoid the extra vertical space (which is deployed in the first paragraph of the previous image) reads:

``` css
a.footnote-ref { vertical-align: text-top; font-size: 75%; }
```

@mb21 proposes the following approaches:

``` css
a.footnote-ref { vertical-align: top; font-size: 0.6em; }
a.footnote-ref { vertical-align: top; position: relative; top: -0.5em; }
```

Which one is the best? I have uploaded an ePub file ([footnotes.zip](https://github.com/jgm/pandoc/files/1839261/footnotes.zip) [please, rename the extension from `.zip` to `.epub` to get it working]) that contains the four options.

If you could check with your reader device and report which one is the best (and which ones aren’t working as expected, this could help to improve the appearance of footnote references in ePub.

**Comment by mb21** [comment]
and yet [another](https://css-tricks.com/snippets/css/prevent-superscripts-and-subscripts-from-affecting-line-height/):

```
a.footnote-ref { vertical-align: baseline; position: relative; top: -0.4em; }
```

**Comment by ousia** [comment]
@mb21, I updated the ePub document with the fifth option.

**Comment by mb21** [comment]
What to you think @Porges?

**Comment by jzeneto** [comment]
Ressurrecting this issue, there's another option: the one suggested in [Blitz Tricks](https://friendsofepub.github.io/eBookTricks/#typo-sup):

```css
.footnote-ref {
  font-size: 0.675em;
  line-height: 1.2;
  vertical-align: super;
  vertical-align: 35%;
}
```

I can confirm this styling works as OP expects in Foliate (2.5.0), Calibre (5.10) and Kindle 10.

**Comment by jgm** [comment]
I don't understand this CSS.  The second `vertical-align` doesn't just override the first?

**Comment by jzeneto** [comment]
Yes... I've tested here, and either value (`super` or `35%`) is valid, although `super` lifts the number up a little more. With either value, line height (of surrounding text) is not affected, which is what this issue calls for.

Sorry for the duplicating value. I would stick with `vertical-align: super`, which is clearer.

**Comment by jzeneto** [comment]
One can also use a little of feature queries to get even better typography on supporting reading systems:

```css
@supports (font-feature-settings: "sups") {
  .footnote-ref {
    font-size: inherit;
    line-height: inherit;
    vertical-align: inherit;
    font-feature-settings: "sups";
  }
}
```

In this case, the OpenType `sups` feature is used.
