### ISSUE TITLE
revealjs: cannot set background in title slide

### ISSUE THREAD

**Issue by tlvince** [jgm/pandoc#4498]
Following [Background in reveal.js](http://pandoc.org/MANUAL.html#background-in-reveal.js), the following syntax can be used to set a background image (etc.) on a particular slide:

```mdhe
# Slide {data-background-image='/images/bg.jpg'}
```

Is there an equivalent for the title slide (i.e. the slide derived from the [metadata block](http://pandoc.org/MANUAL.html#metadata-blocks))? I expected the following to work, to no avail.

```yaml
---
title: My talk
author: \@tlvince
date: 2018-03-26
data-background-image: /images/bg.jpg
---
```

```
❯ pandoc -v
pandoc 2.1.3
```
