### ISSUE TITLE
Powerpoint output: images in master slides result an empty duplicate in output

### ISSUE THREAD

**Issue by rich-iannone** [jgm/pandoc#4827]
The full minimal reproducible example can be downloaded here: [test.zip](https://github.com/jgm/pandoc/files/2275359/test.zip)

pwrpnt.md:

````
---
title: "Untitled"
output:
  powerpoint_presentation:
    reference_doc: template.potx
---

# Title Slide

Title

## Second Slide

- bullet 1
- bullet 2
````

template.potx is within the zip file (cannot be attached here).

The following is run at command line (with pandoc 2.2.1):

```
pandoc +RTS -K512m -RTS pwrpnt.md --to pptx --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output pwrpnt.pptx --reference-doc template.potx
```

Here's a screenshot of the output .pptx (where I dragged the second image frame to the lower right):

<img width="1224" alt="powerpoint_image_master" src="https://user-images.githubusercontent.com/5612024/43917375-05bc7dac-9bc5-11e8-8ccb-9487b9ad7656.png">

The issue is the non-necessary image (which cannot find the image anyway) that appears in the same position as the image in the master slide. The user can manually delete those extra image frames though.
