### ISSUE TITLE
Some write formats render citations, some do not.

### ISSUE THREAD

**Issue by dhimmel** [jgm/pandoc#4834]
I've been working on https://github.com/greenelab/manubot/issues/48, where we are using Pandoc to create a reference list from CSL JSON Data and a CSL XML Style. We are passing stdin to Pandoc like the following:

```yaml
---
{
  "nocite": "@*",
  "csl": "https://github.com/greenelab/manubot-rootstock/raw/master/build/assets/style.csl",
  "references": [
    {
      "archive_location": "1806.05726v1",
      "version": "1",
      "URL": "https://arxiv.org/abs/1806.05726v1",
      "title": "Generalization of the Fermi Pseudopotential",
      "issued": {
        "date-parts": [
          [
            2018,
            6,
            14
          ]
        ]
      },
      "author": [
        {
          "literal": "Trang T. Le"
        },
        {
          "literal": "Zach Osman"
        },
        {
          "literal": "D. K. Watson"
        },
        {
          "literal": "Martin Dunn"
        },
        {
          "literal": "B. A. McKinney"
        }
      ],
      "container-title": "arXiv",
      "type": "report",
      "id": "10GH4uYUR"
    }
  ]
}
...
```

Locally, I've saved this text in a file named `header.yaml`. When I run pandoc with different `--to` options, sometimes the citations are rendered, sometimes they are not. For example, the following commands produce a blank output:

```
cat header.yaml | pandoc --filter pandoc-citeproc --to=markdown
cat header.yaml | pandoc --filter pandoc-citeproc --to=jats
```

However, other options render the citations. For example, here is the output with `--to=plain`

```
1. GENERALIZATION OF THE FERMI PSEUDOPOTENTIAL
Trang T. Le, Zach Osman, D. K. Watson, Martin Dunn, B. A. McKinney
_arXiv_ (2018-06-14) https://arxiv.org/abs/1806.05726v1
```

Output with `--to=markdown_strict`

```
1. **Generalization of the Fermi Pseudopotential**  
Trang T. Le, Zach Osman, D. K. Watson, Martin Dunn, B. A. McKinney  
*arXiv* (2018-06-14) <https://arxiv.org/abs/1806.05726v1>
```

I'm using pandoc 2.2.1. I didn't see anything in the documentation about which output formats render citations. Is there an a priori way to know whether a format supports citation rendering? Is there a way to force a format to render the citations, even if it doesn't by default?

**Comment by jgm** [comment]
All output formats work with citations.

You're not seeing anything for `-t markdown`, because you aren't using `-s` (standalone).  If you use `-s`, you'll get the metadata rendered, and you'll see this:

```
---
csl: 'https://github.com/greenelab/manubot-rootstock/raw/master/build/assets/style.csl'
nocite: '@*'
references:
- URL: 'https://arxiv.org/abs/1806.05726v1'
  archive_location: '1806.05726v1'
  author:
  - literal: 'Trang T. Le'
  - literal: Zach Osman
  - literal: 'D. K. Watson'
  - literal: Martin Dunn
  - literal: 'B. A. McKinney'
  container-title: arXiv
  id: 10GH4uYUR
  issued:
    date-parts:
    - - 2018
      - 6
      - 14
  title: Generalization of the Fermi Pseudopotential
  type: report
  version: 1
---
```

This is a direct markdown translation of your input.  If instead you'd like *rendered* markdown citations, you need to tell pandoc to disable the `citation` extension for the output markdown, by doing `-t markdown-citations`.  With `+citation`  -- the default -- then pandoc assumes you're targeting a markdown format that supports pandoc-style citations, and it will just use those in the output instead of rendering.  (This also explains why `markdown_strict` gives you rendered citations: `markdown_strict` doesn't enable the `citation` extension.)

With `jats`, the issue can also be resolved by adding `-s`.  For jats, we can't just tag the bibliography onto the body, as we do in other formats, since it has to be outside the `<body>` element in a special `<back>` element.  So we pass the bibliography to the template.  If you don't use `-s`, the template is bypassed.

Hope that explains what you're seeing.  Closing, because not a bug.
