### ISSUE TITLE
linestretch option ignored when lang=ko is set

### ISSUE THREAD

**Issue by esnahn** [jgm/pandoc#5179]
![snipaste_2018-12-26_22-02-50](https://user-images.githubusercontent.com/1122053/50446764-09f0e680-095a-11e9-9b61-4d99253b7252.png)

Pandoc version:

```
pandoc.exe 2.5
Compiled with pandoc-types 1.17.5.4, texmath 0.11.1.2, skylighting 0.7.4
```

With the command:

```
pandoc "$(STYLEDIR)/template_test.yaml" "$(INPUTDIR)"/14*.md \
	-o "$(OUTPUTDIR)/$(STDNO)-$(FULLNAME)-Thesis-test.pdf" \
	--pdf-engine=xelatex
```

with file template_test.yaml as below:

```
---
lang: ko # BCP 47 tag for Korean
# this option changes everything back to default...

linestretch: 3
# indent: true

fontfamilies: # for xetex and polyglossia
  - name: \hangulfont
    font: NanumMyeongjo
    options:
      - Script = Hangul
      - Path = style/fonts/
      - Extension = .otf
      - BoldFont = *Bold 
  - name: \hangulfontsf
    font: NanumBarunGothic
    options:
      - Script = Hangul
      - Path = style/fonts/
      - Extension = .otf
      - BoldFont = *Bold 
  - name: \hangulfonttt
    font: D2Coding
    options:
      - Path = style/fonts/
      - Extension = .ttf
      - BoldFont = *Bold 
---

```

`linestretch` option is respected only when `lang` is not set `ko`.
lang=en and lang=it have no problem.

**Comment by jgm** [comment]
I suspect that if you look at the intermediate tex
file that pandoc generates (which you can see by
adding --verbose), you'll see that linestretch
is not ignored by pandoc; an appropriate command
like `\setstretch{3}` is added.  Probably this doesn't
work with the Korean font for some reason.  You may
need to ask on a LaTeX forum to clear this up, posting
a minimal tex example.

In any case I don't think it's a problem with pandoc,
specifically.

**Comment by esnahn** [comment]
It is definitely not the font because it happens too with korean font and text.

![snipaste_2018-12-27_14-13-45](https://user-images.githubusercontent.com/1122053/50466593-d5c10880-09e1-11e9-8b29-040cd9d60c4e.png)

with addition of [main/sans/mono]font of course, otherwise it wouldn't run because of missing characters:

```
---
lang: ko # BCP 47 tag for Korean
# this option changes everything back to default...

linestretch: 3
# indent: true

fontfamilies: # for xetex and polyglossia
  - name: \hangulfont
    font: NanumMyeongjo
    options:
      - Script = Hangul
      - Path = style/fonts/
      - Extension = .otf
      - BoldFont = *Bold 
  - name: \hangulfontsf
    font: NanumBarunGothic
    options:
      - Script = Hangul
      - Path = style/fonts/
      - Extension = .otf
      - BoldFont = *Bold 
  - name: \hangulfonttt
    font: D2Coding
    options:
      - Path = style/fonts/
      - Extension = .ttf
      - BoldFont = *Bold 

mainfont: NanumMyeongjo
mainfontoptions:
  - Path = style/fonts/
  - Extension = .otf
  - BoldFont = *Bold 
sansfont: NanumBarunGothic
sansfontoptions:
  - Path = style/fonts/
  - Extension = .otf
  - BoldFont = *Bold 
monofont: D2Coding
monofontoptions:
  - Path = style/fonts/
  - Extension = .ttf
  - BoldFont = *Bold 

---
```

I'm a beginner with latex (learning only because to use with pandoc) so I'm not saying that the broken part is pandoc's but wanted to just share the problem and what is not. (in this case the font)
