### ISSUE TITLE
fontfamilies doesn't accept a list of options

### ISSUE THREAD

**Issue by esnahn** [jgm/pandoc#5194]
In other words, there is no for loop for fontfamilies.options, unlike [main/sans/mono]font.

In the template, fontfamilies does `\newfontfamily{$fontfamilies.name$}[$fontfamilies.options$]{$fontfamilies.font$}`, while mainfont does `\setmainfont[$for(mainfontoptions)$$mainfontoptions$$sep$,$endfor$]{$mainfont$}`.

So you CAN'T do this with fontfamilies:
```
fontfamilies:
  - name: \hangulfont
    font: NanumMyeongjo
    options:
      - Path = style/fonts/
      - Extension = .otf
      - BoldFont = *Bold 
```

Although you can do this with mainfont:
```
mainfont: NanumMyeongjo
mainfontoptions:
  - Path = style/fonts/
  - Extension = .otf
  - BoldFont = *Bold 
```

And this patch would fix it!
https://github.com/adunning/pandoc/commit/fc9ac7993a93e078b0c5fa8a2c9011e444393f87
