### ISSUE TITLE
Duplicate parenthesis in econometrica csl

### ISSUE THREAD

**Issue by luispfonseca** [jgm/pandoc#5467]
MWE:
`main_text.md` file:
```
---
references:
- type: article-journal
  id: WatsonCrick1953
  author:
  - family: Watson
    given: J. D.
  - family: Crick
    given: F. H. C.
  issued:
    date-parts:
    - - 1953
      - 4
      - 25
  title: 'Molecular structure of nucleic acids: a structure for deoxyribose
    nucleic acid'
  title-short: Molecular structure of nucleic acids
  container-title: Nature
  volume: 171
  issue: 4356
  page: 737-738
  DOI: 10.1038/171737a0
  URL: http://www.nature.com/nature/journal/v171/n4356/abs/171737a0.html
  language: en-GB
csl: econometrica.csl
...

# First section
This is a paper @WatsonCrick1953

# References
::: {#refs}
:::
```

`econometrica.csl` from https://www.zotero.org/styles/econometrica

Compilation:
```
pandoc --filter pandoc-citeproc main_text.md -o main_text.pdf
```

Output in pdf:
```
This is a paper Watson and Crick ((1953))
```

Expected output:
```
This is a paper Watson and Crick (1953)
```

Is there a way around this? I tried changing the csl file to remove the parenthesis, but they'd also be removed from the references section.
