### ISSUE TITLE
Change font size of monospace font

### ISSUE THREAD

**Issue by ad-si** [jgm/pandoc#5491]
I have following markdown file:

~~~md
---
fontsize: 10pt
monofontoptions: 'Scale=0.7'
...

This is just some text.

```js
var test = "And some code"
```
~~~

and compile it with

```sh
pandoc --pdf-engine xelatex test.md -o test.pdf
```

The monospace font should be smaller, but it isn't. (This is also what https://bookdown.org/yihui/bookdown/publishers.html is using)
I also tried it with other pdf-engines, but it doesn't change anything.

Any ideas?

**Comment by ad-si** [comment]
Look at that … when I explicitly set the font before `monofontoptions` with 
```yaml
monofont: 'Source Code Pro'
```
it suddenly works.
This looks awfully like a bug ^^

**Comment by jgm** [comment]
Look at the template:

```
$if(monofont)$
  \setmonofont[$for(monofontoptions)$$monofontoptions$$sep$,$endfor$]{$monofont$}
$endif$
```

When no mono font is set, there's nowhere to put monofontoptions.  (In this case we're using LaTeX defaults.)  I don't think it's a bug.

**Comment by ad-si** [comment]
And why isn't `$monofont` set to a default value otherwise?

**Comment by kwk** [comment]
Just for your interest, I have created a bunch of font size classes that I can apply to individual fenced-code pieces:

```yaml
pandoc-latex-fontsize:
  - classes: [Huge]
    size: Huge
  - classes: [huge]
    size: huge
  - classes: [LARGE]
    size: LARGE
  - classes: [Large]
    size: Large
  - classes: [large]
    size: large
  - classes: [normalsize]
    size: normalsize
  - classes: [small]
    size: small
  - classes: [footnotesize]
    size: footnotesize
  - classes: [scriptsize]
    size: scriptsize
  - classes: [tiny]
    size: tiny
```

So in essence I can then write:

``````
```tiny
This is some very wide code that needs to be small in order to fit the screen.
```
``````

Here you can find out how to install and use the filter with pandoc: https://github.com/chdemko/pandoc-latex-fontsize
