### ISSUE TITLE
Two dashes in URL (references) is processed as long dash

### ISSUE THREAD

**Issue by somenxavier** [jgm/pandoc#5596]
I have
```
- type: "book"
  id: "from-principles-en"
  author:
  - family: "NTCM"
    given: ""
  publisher: "National Council of Teachers of Mathematics (NCTM)"
  title: "Principles to Actions: Ensuring Mathematical Success for All"
  issued:
     year: "2014"
  URL: "http://www.nctm.org/Store/Products/Principles-to-Actions--Ensuring-Mathematical-Success-for-All/"
```
in `references` in YAML block.
After convert markdown to html5, I get,
```
    <p>NTCM. 2014. <em>Principles to Actions: Ensuring Mathematical Success for All</em>. National Council of Teachers of Mathematics (NCTM). <a href="http://www.nctm.org/Store/Products/Principles-to-Actions–Ensuring-Mathematical-Success-for-All/">http://www.nctm.org/Store/Products/Principles-to-Actions–Ensuring-Mathematical-Success-for-All/</a>.</p>
```

See long dash between `Actions` and `Ensuring`
Which is not ASCII only URL encoding
