### ISSUE TITLE
Fallback-search "user data directory" for defaults FILE options

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc#5982]
In the defaults YAML files, for known file kinds (filters, templates etc.), Pandoc will search in the relevant subdirectory of its `data-dir`. But for other FILE-based options, e.g. `reference-doc`, it seems you cannot rely on `data-dir` to keep these files unless you specify an absolute path:

```yaml
filters: modifyHeadings.lua # works
reference-doc: custom.docx # fails
csl: csl/apa.csl # fails
```

In this case, `modifyHeadings.lua` auto-resolves to `$data-dir/filters`, whereas `custom.docx` can only be used if it is in the current working directory, but is not additionally searched for in `$data-dir` . `csl` is another example. All this works with absolute paths, but these are fragile. One workaround solution would be to consider #5977 (being able to expand $HOME env variable), but having the pandoc user directory as a fallback search location simplifies the path descriptions even more.
