### ISSUE TITLE
JATS citations

### ISSUE THREAD

**Issue by tarleb** [jgm/pandoc#6013]
JATS citations currently don't link to the actual reference. The JATS writer code contains a note which reads "TODO revisit this after examining the jats.csl pipeline". I also noticed a commit which added support, but which was reverted.

I would like to add this feature, but there appear to be pitfalls which I'm not aware of yet. What would be a good way to approach this?

**Comment by jgm** [comment]
I can't recall why that commit was reverted.  So, go ahead, but make sure to validate everything against external JATS validty testers.

**Comment by tarleb** [comment]
I think now I see the cause for this: it looks like the jats.csl should handle xref creation fully, but it doesn't seem to work for whatever reason. Now trying to figure out what goes wrong there.

**Comment by gabestein** [comment]
Hello! We're facing this issue now with trying to generate good JATS with PubPub. Was there every any resolution to generating JATS with xrefs? If not, @tarleb, this is potentially something our team could take a look at if you wanted to point us in the right direction.

**Comment by jgm** [comment]
I'm not sure; we got rid of jats.csl and we don't use it any more, so maybe this issue is obsolete?  @gabestein what version of pandoc are you using?

**Comment by gabestein** [comment]
We just upgraded to 2.14.2, so, the latest.

**Comment by jgm** [comment]
Can you give a brief sample of the kind of output you'd expect?

**Comment by gabestein** [comment]
Sure! So, right now, if we have a markdown file that contains a citation in the metadata and a reference in the text:

```
---
title: JATS xref Sample
author:
  - PubPub Team
copyright:
  link: "https://creativecommons.org/licenses/by/4.0/"
  text: Creative Commons Attribution 4.0 International License
  type: CC-BY
date: Sep 13, 2021
journal:
  title: PubPub Demo Site
references:
  - _graph:
      - data: |
          \@inproceedings{Tukey1966Data, journal = {Proceedings of the
          november 7-10, 1966, fall joint computer conference}, doi =
          {10.1145/1464291.1464366}, title = {Data analysis and statistics:
          An expository overview}, url =
          {https://doi.org/10.1145/1464291.1464366}, author = {Tukey, John
          W. and Wilk, Martin B.}, pages = {695\--709}, date = {1966}, year
          = {1966}, }
        type: \@bibtex/text
      - type: \@else/list+object
      - data:
          label: Tukey1966Data
          properties:
            author: Tukey, John W. and Wilk, Martin B.
            date: 1966
            doi: 10.1145/1464291.1464366
            journal: Proceedings of the november 7-10, 1966, fall joint
              computer conference
            pages: 695--709
            title: "Data analysis and statistics: An expository overview"
            url: "https://doi.org/10.1145/1464291.1464366"
            year: 1966
          type: inproceedings
        type: \@bibtex/object
      - type: \@csl/list+object
    author:
      - family: Tukey
        given: John W.
      - family: Wilk
        given: Martin B.
    citation-label: Tukey1966Data
    container-title: Proceedings of the november 7-10, 1966, fall joint
      computer conference
    DOI: 10.1145/1464291.1464366
    id: Tukey1966Data
    issued:
      date-parts:
        - - 1966
    page: 695-709
    title: "Data analysis and statistics: An expository overview"
    type: paper-conference
    URL: "https://doi.org/10.1145/1464291.1464366"
    year-suffix: Data
---

"Nothing---not the careful logic of mathematics, not statistical models
and theories, not the awesome arithmetic power of modern
computers---nothing can substitute here for the flexibility of the
informed human mind," wrote [@Tukey1966Data] half a century ago.
```

It outputs the following around the in-text reference, properly turning the markdown reference into a Chicago style parenthetical, but without the JATS xref tag:

```
<p>“Nothing—not the careful logic of mathematics, not statistical models
and theories, not the awesome arithmetic power of modern
computers—nothing can substitute here for the flexibility of the
informed human mind,” wrote (Tukey and Wilk 1966) half a century
ago.</p>
```

We would expect a JATS xref tag with the corresponding id (pandoc seems to prepend `ref-`):

```
<p>“Nothing—not the careful logic of mathematics, not statistical models
and theories, not the awesome arithmetic power of modern
computers—nothing can substitute here for the flexibility of the
informed human mind,” wrote <xref ref-type="bibr" rid="ref-Tukey1966Data">(Tukey and Wilk 1966)</xref> half a century
ago.</p>
```
