### ISSUE TITLE
Defaults override YAML Metadata

### ISSUE THREAD

**Issue by jaybe-jekyll** [jgm/pandoc#6142]
Summary:

While command-line arguments override Defaults and YAML Metadata, values within a Defaults file do not override the content YAML Metadata when present.

Example:

- ./content/my-article.md

```yaml
title: My Fancy Title
subtitle: All your bases are belong to us
author: Mr. Author
... etc.
```

- ./defaults/default.yaml

```yaml
metadata:
  author:
  - Default Author
  title: Default Title
  subtitle: Default Subtitle
... etc.
```

The values in Defaults take precedence over the YAML Metadata present in the article.

Does it make sense to allow available YAML Metadata within a file for conversion (e.g. article.md) to override the Defaults file specified?

e.g. `pandoc --data-dir -d default my-article.md -o file.html`

The logic is to capture defaults within the Defaults file that may otherwise not be set by an author within a content file... such as:

```yaml
metadata:
  lang: en-US

**Comment by jgm** [comment]
I see why you might think it should behave this way.  The idea, though, is that defaults function as default command-line arguments.  And currently, `--metadata` specified on the command line always take precedence over metadata specified in a file.  We could change that, but I think that would be unexpected and might break things for some users.

**Comment by alerque** [comment]
At the very least "defaults" is the wrong name for something that takes priority over explicitly set values!

I think there should be more stages to the fallback process in general.

1. External defaults file (file specified in cmd args)
2. Explicit in-file meta data
3. Explicitly loaded external meta data file
4. Values set individually in command line args

Each step should override any values found before. Currently ③ is being done but is miss-named as ①, and there is no ① at all.

**Comment by jgm** [comment]
These are *defaults for things you can specify on the command line*; they behave as if you'd put them on the command line. You wouldn't be surprised to find that specifying `--metadata foo=bar` on the command line overrides `foo` in your document, would you? That is how it has always worked.  Well, that's exactly what happens when you put it in your defaults file.

If you want to include metadata fallbacks and allow your document to override them, put the metadata in a metadata file (`metadata-file` in defaults or `--metadata-file` on the command line), and you'll find it works the way you want here.

**Comment by jaybe-jekyll** [comment]
Thanks for the explanation and additional insight.

Using `metadata-file` is reasonable enough once understood.

My goal was to have a *default fallback* for when an author (me, being lazy) does not populate YAML Metadata within a document.

> However...

For thoroughness and information sharing... note that an exception to this behavior appears if/when not specifying a `title:` in YAML Metadata and or a `--metadata title: My Title` on the command line.

The following results in *not* including `title:` in YAML metadata within content or on command line, while having `metadata: ...title:` populated and included via `metadata-files: ...boilerplate.yaml`:

```sh
[WARNING] This document format requires a nonempty <title> element.
  Defaulting to '20200212114015-my-fancy-title' as the title.
  To specify a title, use 'title' in metadata or --metadata title="...".
```

> Further...

If specifying `title:` within the content YAML Metadata but not specifying `date:`, `author:`, etc. ... then the `header` produces the title however does not produce the `date` and `author` values (HTML output)... *even with those values populated within the `metadata-file: ... - boilerplate.yaml`:

```yaml
metadata:
  author:
  - Default Author
  lang: en-US
  title: Default Title
  subtitle: Default Subtitle
  date: 1970-01-01
title-prefix: Default Title Prefix
```

**Comment by jaybe-jekyll** [comment]
Ah!

So, the `metadata-file` must be such as--

```yaml
author: Default Author
lang: en-US
title: Default Title
subtitle: Default Subtitle
date: 1970-01-01
title-prefix: Default Title Prefix
```

and *not* as within the `defaults` file as--

```yaml
metadata:
  author:
  - Default Author
  lang: en-US
  title: Default Title
  subtitle: Default Subtitle
  date: 1970-01-01
title-prefix: Default Title Prefix
```

It must be *just* like YAML Metadata within the content/article itself.

When done this way, default values *can* be specified and as fallbacks if not populated within the content YAML Metadata.

Please note that this *also* works for the `title:` value... even if *not* specified within the YAML Metadata AND OR via the command line!

👍
