### ISSUE TITLE
Template prints "true" instead of author name.

### ISSUE THREAD

**Issue by amaridev** [jgm/pandoc#6179]
Hi,
I might need some help. When using the default template, the first front page where the authors name should be, reads true. (pandocs markdown to pdf output)

Using the yaml metadata block I've written the following block which leads to my problem:
```
author:
- name: "Max Mustermann"
  affiliation: "University xy"
  email: mail@domain.com
``` 

I figured out, if I only use author: "Max Mustermann" for example. Everything is fine. But together with affiliation and email as seen in a couple of examples, it won't work for me.
