### ISSUE TITLE
[citeproc] DOIs with "https://doi.org/" prefix

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc#6723]
Many style guides, including the Chicago Manual, require DOIs in bibliographies to be shown with a `https://doi.org/` prefix. Unlike pandoc 2.10.1 and earlier, the most recent pandoc (2.11) from the master branch outputs this prefix, but does not include it in the actual link. The DOI part itself is still clickable, but the appearance is weird, in particular if the DOI part but not the prefix is coloured and/or underlined, as in latex or html output.

MWE, including both a regular DOI and a [shortDOI](http://shortdoi.org/):

```
pandoc -C -t markdown-citations <<EOT

Blah [@doe1; @doe2].

# References {-}

---
references:
- id: doe1
  type: article
  author:
  - family: Doe
    given: John
  DOI: 10/abcde
  issued:
    - year: 2020
  title: An article
- id: doe2
  type: article
  author:
  - family: Doe
    given: John
  DOI: 10.1109/5.771073
  issued:
    - year: 2020
  title: Another article
...
EOT
```

Actual output:

```
Blah (Doe 2020a, 2020b).

References {#references .unnumbered}
==========

::: {#refs .references .csl-bib-body .hanging-indent}
::: {#ref-doe1 .csl-entry}
Doe, John. 2020a. "An Article."
https://doi.org/[10/abcde](https://doi.org/10/abcde).
:::

::: {#ref-doe2 .csl-entry}
---------. 2020b. "Another Article."
https://doi.org/[10.1109/5.771073](https://doi.org/10.1109/5.771073).
:::
:::
```

Expected output = output from pandoc 2.10.1:

```
Blah (Doe 2020a, 2020b).

References {#references .unnumbered}
==========

::: {#refs .references .hanging-indent}
::: {#ref-doe1}
Doe, John. 2020a. "An Article." <https://doi.org/10/abcde>.
:::

::: {#ref-doe2}
---------. 2020b. "Another Article." <https://doi.org/10.1109/5.771073>.
:::
:::
```

Same effect with latex and html output formats.

While we’re at it, something else that might be improved is one detail concerning the URL form of shortDOIs:

https://www.doi.org/resources.html states: ”The shortDOI Service is a public service for creating shortcuts to DOI names, which can be very long strings. The service creates short handles of the form 10/abcde and enables short HTTP URIs of the form http://doi.org/abcde that are ideal for use in email, blogs, mobile messaging and more.”

So the shortest URL form of a shortDOI is `https://doi.org/abcde` rather than `https://doi.org/10/abcde`. Would it be possible for pandoc to remove, only for shortDOIs, and only if the CSL style used requests the use of the URL form, the `10/` part?

(As to distinguishing regular DOIs and shortDOIs: shortDOIs invariably begin with `10/` whereas regular DOIs start with `10.`, see [here](https://www.doi.org/doi_handbook/2_Numbering.html).)

**Comment by jgm** [comment]
Here's how linkification works in pandoc:  we alter the values of the variables in the references for DOI, URL, etc., converting them from plain text to formatted pandoc links.  So if DOI is stored as `10.1109/5.771073`, this gets converted to a link with link text `10.1109/5.771073`.

The problem is that some styles, including chicago-author-date, have rules like this:
``` xml
            <if variable="DOI">
              <text variable="DOI" prefix="https://doi.org/"/>
            </if>
```
Once we apply the prefix, we get plain text `https://doi.org/` followed by linkified `10.1109/5.771073`.  I  agree that this looks bad, but it's hard to know how to handle this, given that linkification occurs prior to calling `citeproc`, and the prefix is applied by `citeproc`.

You might say:  just have `citeproc` encode a rule to include the prefix in the linked text if the variable is a link.  But this isn't possible, because links aren't an official part of CSL, and `citeproc` has no notion of them.  (You can pass them through since `citeproc` can accept various kinds of formatted text, but they are "opaque.")

I will fix the short DOI thing. That is easy.

**Comment by jgm** [comment]
I guess I could have pandoc walk the tree at the end and look for text `https://...` followed by a link with that prefix in the URL, and incorporate it.  This is a band-aid approach, which is ugly and will harm performance a bit, but maybe worth while.

**Comment by njbart** [comment]
Great – in bibliographies this works nicely, but it seems in footnotes, the `https://doi.org/` prefix is not being incorporated into the link yet:

```
pandoc -C -t markdown-citations <<EOT

Blah [@doe].

# References {-}

---
csl: chicago-fullnote-bibliography.csl
references:
- id: doe
  type: article
  author:
  - family: Doe
    given: John
  DOI: 10.1109/5.771073
  issued:
    - year: 2020
  title: An article
...
EOT
```

Actual output:

```
Blah.[^1]

References {#references .unnumbered}
==========

::: {#refs .references .csl-bib-body .hanging-indent}
::: {#ref-doe .csl-entry}
Doe, John. "An Article," 2020. <https://doi.org/10.1109/5.771073>.
:::
:::

[^1]: John Doe, "An Article," 2020,
    https://doi.org/[10.1109/5.771073](https://doi.org/10.1109/5.771073).
```

Expected:

```
Blah.[^1]

References {#references .unnumbered}
==========

::: {#refs .references .csl-bib-body .hanging-indent}
::: {#ref-doe .csl-entry}
Doe, John. "An Article," 2020. <https://doi.org/10.1109/5.771073>.
:::
:::

[^1]: John Doe, "An Article," 2020,
    <https://doi.org/10.1109/5.771073>.

```
