### ISSUE TITLE
[citeproc] narrative citations & footnote style: editor(s) wrongly appear in narrative

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc#6765]
In narrative citations (where the author name is incorporated into the text as part of the sentence) and using a footnote style (including but not limited to the two listed in the MWE), editor(s) wrongly appear in the text rather than in the footnote.

MWE:

```
pandoc -C -t plain << EOT

@book_chapter_1 [55] says blah.

---
csl: chicago-fullnote-bibliography.csl
# csl: modern-humanities-research-association.csl
references:
- id: book_chapter_1
  author:
    - family: Author
      given: Ann
  container-title: A book
  editor:
    - family: Editor
      given: Edward
  issued: 2014
  page: 48-67
  publisher: A publisher
  publisher-place: A place
  title: A book chapter
  type: chapter
...
EOT
```

Actual output:

```
pandoc 2.11.0.2
Compiled with pandoc-types 1.22, texmath 0.12.0.3, skylighting 0.10.0.2,
citeproc 0.1.0.2, ipynb 0.1
[...]

Ann Authored. Edward Editor[1] says blah.

Author, Ann. “A Book Chapter.” In A Book, edited by Edward Editor,
48–67. A place: A publisher, 2014.

[1] “A Book Chapter,” in A Book (A place: A publisher, 2014), 55.
```

Expected output = output from pandoc 2.10 with pandoc-citeproc:

```
Ann Author[1] says blah.

Author, Ann. “A Book Chapter.” In A Book, edited by Edward Editor,
48–67. A place: A publisher.

[1] “A Book Chapter,” in A Book, ed. Edward Editor (A place: A
publisher), 55.
```
