### ISSUE TITLE
Punctuation moving with author-in-text citations in footnotes

### ISSUE THREAD

**Issue by mattlynskey** [jgm/pandoc#6835]
I am using Pandoc 2.11.1.1.

When I process the BibTex Key (via Zotero) through Pandoc (DocDown) I end up with citations like below:

[1] Kearney, “Introduction.”, xvi.
[2] Kearney, "Introduction.", 3.

Notice the punctuation issue. There is an odd period inserted in the quotation marks and the comma occurs outside the quotations marks. It seems to happen with **journal articles/book sections** that have quotation marks but works fairly good with books which get italicized. I am using chicago-note-bibliography-always-short.csl (https://gist.github.com/denismaier/21168acf9e9287fc41f32c7351917111).

The citations should look like this:

[1] Kearney, “Introduction,” xvi.
[2] Kearney, "Introduction," 3.

See thread here for test files (.md, .docx, .csl): https://groups.google.com/g/pandoc-discuss/c/wybUIKpmYUE.

**Comment by jgm** [comment]
Here's a more self-contained example.
test.md:
```
---
nocite: '[@*]'
references:
- id: KearneyIntroduction2006
  author:
  - family: Kearney
    given: Richard
  collection-title: Thinking in action
  container-title: On translation
  doi: 10.7202/016668ar
  issued: 2006
  keyword: Translating and interpreting
  page: xx, 46 pages
  publisher: Routledge
  publisher-place: London
  title: Introduction
  translator:
  - family: Brennan
    given: Eileen
  type: chapter
...

Blah blah [@KearneyIntroduction2006, p. xvi].

Test [^4]

[^4]: @KearneyIntroduction2006, xvi.
```

Command
```
pandoc test.md --citeproc -t plain -s --csl chicago-note-bibliography.csl
```
Output:
```
Blah blah.[1]

Test[2]

Kearney, Richard. “Introduction.” In On Translation, translated by
Eileen Brennan, xx, 46 pages. Thinking in Action. London: Routledge,
2006. doi:10.7202/016668ar.

[1] Kearney, “Introduction,” xvi.

[2] Kearney, “Introduction.”, xvi.
```
