### ISSUE TITLE
Incorrect rendering of URL in references

### ISSUE THREAD

**Issue by funveen** [jgm/pandoc#6874]
I am using pandoc 2.11.2 with citeproc 0.2 and an URL containing two subsequent dashes `--` within a reference is not rendered correctly (markdown to PDF). Usually, I provide references via BibLaTeX file, but the same behaviour appears with YAML references as in this MWE:

```
---
title: "My Document"
references:
- type: article-journal
  id: Watson1953
  author: Watson
  issued: 1953
  title: 'Molecular structure of nucleic acids'
  URL: https://127.0.0.1/documents/Watson--paper.pdf
---

# Headline

Text with reference [@Watson1953].

# References
```

When processed with `pandoc --citeproc -o test.pdf test.md` the PDF result looks like `https://127.0.0.1/documents/Watson/T1/textendash paper.pdf` and cannot be called anymore.

- In the intermediate tex file the double dash is already rendered as en dash: `https://127.0.0.1/documents/Watson–paper.pdf` 
- Replacing the double dash with URL encoding `%2D%2D` is a workaround using YAML references, but will make things worse if BibLaTeX files are used (URL will be cut off after `Watson`).
- This error did not appear in pandoc 2.10 with pandoc-citeproc 0.17.0.1.
