### ISSUE TITLE
docx reader doesn't pick up bibliography style

### ISSUE THREAD

**Issue by denismaier** [jgm/pandoc#6881]
I seems the paragraph style `bibliography` is not recognized by pandoc.

I have converted this simple test file to docx:

```
---
references:
- type: article-journal
  id: WatsonCrick1953
  author:
  - family: Watson
    given: J. D.
  - family: Crick
    given: F. H. C.
  issued:
    date-parts:
    - - 1953
      - 4
      - 25
  title: 'Molecular structure of nucleic acids: a structure for
    deoxyribose nucleic acid'
  title-short: Molecular structure of nucleic acids
  container-title: Nature
  volume: 171
  issue: 4356
  page: 737-738
  DOI: 10.1038/171737a0
  URL: https://www.nature.com/articles/171737a0
  language: en-GB
...

Test [@WatsonCrick1953].
```

Then, I’ve converted the result back to markdown. The bibliography gets converted as a regular paragraph. With `-f docx+styles` the style will be preserved, but I think that style should be preserved out of the box as “Bibliography” as it is one of pandoc’s native styles.

(Pandoc version is 2.11.1.1)
