### ISSUE TITLE
Empty citations element for citations in footnotes

### ISSUE THREAD

**Issue by crsh** [jgm/pandoc#6890]
Hi there, I hope this is the right place to ask about this. I have recently [noticed](https://github.com/crsh/papaja/issues/427) that the AST for citations in the main text and in footnotes differs. In short, the `citations` element of the `Cite` note is empty in footnotes. For contexxt, I came across this, because I've built a filter to modify the citation text based on the `mode` information in `citations`. This filter works with `pandoc-citeproc` but fails with `citeproc` because the information is missing.

Here's how I produced and diagnosed the issue. I used the following document to compare the AST of a regular citation and another one in a footnote (it doesn't seem to matter whether they are in text or not):

~~~
---
bibliography      : bib.bib
---

@fruchtel-sozialer-2013a

Some text [^1].

[^1]: Some text with two references @fruchtel-sozialer-2013a.
~~~

This is the contents of `bib.bib`:

~~~bibtex
@book{fruchtel-sozialer-2013a,
  title = {Sozialer Raum und Soziale Arbeit Fieldbook: Methoden und Techniken},
  author = {Früchtel, Frank and Budde, Wolfgang and Cyprian, Gudrun},
  date = {2013},
  edition = {3},
  publisher = {{Springer VS}},
  location = {{Wiesbaden, Germany}},
  annotation = {OCLC: 811587862},
  isbn = {978-3-531-19047-1 978-3-531-18433-3},
  keywords = {methodology,social,social-work,space,textbook},
  langid = {german}
}
~~~

I used the following filter to print the information in the AST for each:

~~~lua
function debug_filter (el)
  if #el.citations > 0 then
    for key, value in pairs(el) do
        print(key, " -- ", value)
    end
    for key, value in pairs(el.content) do
        for key2,value2 in pairs(value) do
          print(key2, " -- ", value2)
      end
    end
    print(#el.citations)
    for key, value in pairs(el.citations[1]) do
        print(key, " -- ", value)
    end
  else
    for key, value in pairs(el) do
        print(key, " -- ", value)
    end
    for key, value in pairs(el.content) do
        for key2,value2 in pairs(value) do
          print(key2, " -- ", value2)
      end
    end
    print(#el.citations)
  end
  return el
end

return {{Cite = debug_filter}}
~~~

`content` is the same for both citations:

~~~
text	 -- 	Früchtel,
text	 -- 	Budde,
text	 -- 	&
text	 -- 	Cyprian
text	 -- 	(2013)
~~~

`citations` is empty (length 0) for the footnote citation. For the in-text citation it contains the information my filter expects (based on `pandoc-citeproc` behavior):

~~~
prefix	 -- 	table: 0x7f8036407980
id	 -- 	fruchtel-sozialer-2013a
mode	 -- 	AuthorInText
note_num	 -- 	1
hash	 -- 	0
suffix	 -- 	table: 0x7f80364079c0
~~~

Is this desired behavior?

**Comment by jgm** [comment]
It's really a pandoc issue, so transferring.

**Comment by jgm** [comment]
b.md:
```
---
references:
- annote: "OCLC: 811587862"
  author:
  - family: Früchtel
    given: Frank
  - family: Budde
    given: Wolfgang
  - family: Cyprian
    given: Gudrun
  edition: 3
  id: fruchtel-sozialer-2013a
  isbn: 978-3-531-19047-1 978-3-531-18433-3
  issued: 2013
  keyword: methodology,social,social-work,space,textbook
  language: de-DE
  publisher: Springer VS
  publisher-place: Wiesbaden, Germany
  title: "Sozialer Raum und Soziale Arbeit Fieldbook: Methoden und
    Techniken"
  title-short: Sozialer Raum und Soziale Arbeit Fieldbook
  type: book
---

@fruchtel-sozialer-2013a

Some text [^1].

[^1]: @fruchtel-sozialer-2013a
```
```
% pandoc b.md --citeproc -t native
[Para [Cite [Citation {citationId = "fruchtel-sozialer-2013a", citationPrefix = [], citationSuffix = [], citationMode = AuthorInText, citationNoteNum = 1, citationHash = 0}] [Str "Fr\252chtel,",Space,Str "Budde,",Space,Str "and",Space,Str "Cyprian",Space,Str "(2013)"]]
,Para [Str "Some",Space,Str "text",Str ".",Note [Para [Cite [] [Str "Fr\252chtel,",Space,Str "Budde,",Space,Str "and",Space,Str "Cyprian",Space,Str "(2013)"]]],Str ""]
,Div ("refs",["references","csl-bib-body","hanging-indent"],[])
 [Div ("ref-fruchtel-sozialer-2013a",["csl-entry"],[])
  [Para [Str "Fr\252chtel,",Space,Str "Frank,",Space,Str "Wolfgang",Space,Str "Budde,",Space,Str "and",Space,Str "Gudrun",Space,Str "Cyprian.",Space,Str "2013.",Space,Emph [Str "Sozialer",Space,Str "Raum",Space,Str "und",Space,Str "Soziale",Space,Str "Arbeit",Space,Str "Fieldbook:",Space,Str "Methoden",Space,Str "und",Space,Str "Techniken"],Str ".",Space,Str "3rd",Space,Str "ed.",Space,Str "Wiesbaden,",Space,Str "Germany:",Space,Str "Springer",Space,Str "VS."]]]]
```
