### ISSUE TITLE
[citeproc] Bibliography file is not considered when `references` YAML is specified

### ISSUE THREAD

**Issue by mpark** [jgm/pandoc#6951]
Pandoc 2.11

`foo.md`:

```
Refer to [@Patterns] and [@P1260R0]

---
references:
  - id: Patterns
    citation-label: Patterns
    title: "Pattern Matching in C++"
    author:
      - family: Park
        given: Michael
    URL: https://github.com/mpark/patterns
...
```

`index.yaml`:
```
references:
  - id: P1260R0
    citation-label: P1260R0
    title: "Pattern Matching"
    author:
      - family: Michael Park
    issued:
      year: 2018
    URL: https://wg21.link/p1260r0
```

With Pandoc 2.9:
```bash
pandoc foo.md --bibliography index.yaml
<p>Refer to <span class="citation" data-cites="Patterns">(Park, n.d.)</span> and <span class="citation" data-cites="P1260R0">(Michael Park 2018)</span></p>
<div id="refs" class="references hanging-indent" role="doc-bibliography">
<div id="ref-P1260R0">
<p>Michael Park. 2018. “Pattern Matching.” <a href="https://wg21.link/p1260r0">https://wg21.link/p1260r0</a>.</p>
</div>
<div id="ref-Patterns">
<p>Park, Michael. n.d. “Pattern Matching in C++.” <a href="https://github.com/mpark/patterns">https://github.com/mpark/patterns</a>.</p>
</div>
</div>
```

With Pandoc 2.11, it does not find the contents of `index.yaml`.
```bash
pandoc foo.md --citeproc --bibliography index.yaml
[WARNING] Citeproc: citation P1260R0 not found
<p>Refer to <span class="citation" data-cites="Patterns">(Park, n.d.)</span> and <span class="citation" data-cites="P1260R0">(<strong>P1260R0?</strong>)</span></p>
<div id="refs" class="references csl-bib-body hanging-indent" role="doc-bibliography">
<div id="ref-Patterns" class="csl-entry" role="doc-biblioentry">
Park, Michael. n.d. <span>“Pattern Matching in C++.”</span> <a href="https://github.com/mpark/patterns">https://github.com/mpark/patterns</a>.
</div>
</div>
```

The `pandoc-citeproc` behavior was such that the [references are combined](https://github.com/jgm/pandoc-citeproc/blob/b05d286b15b3545faf477301267e1a12be192e87/src/Text/CSL/Pandoc.hs#L238).

If this is intended design for the new built-in citeproc, I'd like to ask to reconsider this decision...
At least for my use case in https://github.com/mpark/wg21, I have a large `index.yaml` of C++ proposals
with which people can cite without explicitly having to add a reference on their own. If they need to add
manual references, however, I do not want the bibliography file to be ignored. Is there an alternative approach
that would work easily with the current behavior?
