### ISSUE TITLE
custom css to change the style of the numberLines class is broken

### ISSUE THREAD

**Issue by ghost** [jgm/pandoc#6957]
In previous versions, in the context of markdown to html rendering, it was possible to add this rule 

```css
a.sourceLine::before {
     text-decoration: none;
}
```

in the file passed as `--css` argument, so that line numbers are not underlined for

    ```{.c .numberLines}
    /* some
    code
    ...*/
    ```

This is broken in most recent versions. Likely at the same time as the commit that caused #6625.
Note that this is trivial to fix

```css
@media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: none; }
}
```
however if something gets reverted for #6625 maybe it could be as well for this.
