### ISSUE TITLE
BibTeX/BibLaTeX writer: Incorrect capitalization of non-English titles

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc#7067]
CSL JSON and CSL YAML expect English-language titles to be stored in sentence case, but BibTeX and BibLaTeX expect them to be in Title Case. 

Upon conversion from CSL JSON/CSL YAML to BibTeX/BibLaTeX, pandoc transforms titles to Title Case – the correct thing to do for English titles.

Non-English titles, however, should never undergo any kind of case transformation. In a CSL JSON/CSL YAML context, these are the titles of items with a `language` tag that does not start with `en`. 

Note that the corresponding tag in BibLaTeX is `langid` rather than `language`.

In BibTeX (which does not have language tags at all), it would seem best to wrap all non-English titles in an extra pair of curly braces in order to prevent any form of case transformation.

Also note that the `pages` field is missing from the BibTeX/BibLaTeX output (in CSL JSON/CSL YAML it’s `page`, not `pages`), and that, somewhat inexplicably, `défrichements` is not capitalized (of course it shouldn’t be in a French title, but in an English title [and otherwise unprotected] it would be wrong not to do so).

Examples (using latest dev):

BibLaTeX:

```
pandoc -f markdown -t biblatex << EOT
---
references:
- id: garaud
  author:
    - family: Garaud
      given: Marcel
  container-title: Bulletin de la Societé des antiquaires de l’Ouest
  collection-title: 4
  issued:
    - year: 1967
  language: fr-FR
  page: 11-27
  title: Recherches sur les défrichements dans la Gâtine poitevine aux XI^e^ et XII^e^ siècles
  type: article-journal
  volume: 9
...
EOT
```

Actual output:

```
@article{garaud,
  author = {Garaud, Marcel},
  title = {Recherches Sur Les défrichements Dans La {Gâtine} Poitevine Aux
{XI}\textsuperscript{e} Et {XII}\textsuperscript{e} Siècles},
  journal = {Bulletin de la Societé des antiquaires de l’Ouest},
  series = {4},
  volume = {9},
  date = {1967},
  language = {fr-FR}
}
```

Expected:

```
@article{garaud,
  author = {Garaud, Marcel},
  title = {Recherches sur les défrichements dans la Gâtine poitevine aux
XI\textsuperscript{e} et XII\textsuperscript{e} siècles},
  journal = {Bulletin de la Societé des antiquaires de l’Ouest},
  series = {4},
  volume = {9},
  pages = {11-27},
  date = {1967},
  langid = {fr-FR}
}
```

BibTeX:

```
pandoc -f markdown -t bibtex << EOT
---
references:
- id: garaud
  author:
    - family: Garaud
      given: Marcel
  container-title: Bulletin de la Société des antiquaires de l’Ouest
  collection-title: 4
  issued: 1967
  language: fr-FR
  pages: 11-27
  title: Recherches sur les défrichements dans la Gâtine poitevine aux XI^e^ et XII^e^ siècles
  type: article-journal
  volume: 9
...
EOT
```

Actual output:

```
  author = {Garaud, Marcel},
  title = {Recherches Sur Les défrichements Dans La {Gâtine} Poitevine Aux
{XI}\textsuperscript{e} Et {XII}\textsuperscript{e} Siècles},
  journal = {Bulletin de la Société des antiquaires de l’Ouest},
  series = {4},
  volume = {9},
  year = {1967}
}
```

Expected:

```
  author = {Garaud, Marcel},
  title = {{Recherches sur les défrichements dans la Gâtine poitevine aux
XI\textsuperscript{e} et XII\textsuperscript{e} siècles}},
  journal = {Bulletin de la Société des antiquaires de l’Ouest},
  series = {4},
  volume = {9},
  pages = {11-27},
  year = {1967}
}
```
