### ISSUE TITLE
LaTeX->HTML: Automatically generate the TOC 

### ISSUE THREAD

**Issue by ip1981** [jgm/pandoc#7237]
If somebody interested: https://github.com/ip1981/pandoc/commit/113479feb55e555a6a114cf6878f9a24c48b3347

With CSS:

```css
.toc h1::before {
  content: "WhatEver";
}
```
