### ISSUE TITLE
CSL entry-spacing="0" not removing vertical space

### ISSUE THREAD

**Issue by rnhmjoj** [jgm/pandoc#7296]
At least with the Latex writer, setting the bibliography property `entry-spacing="0"` in the CSL doesn't completely removes the vertical space between references.

Example document to reproduce the problem:

```
---
title: Issue \#335 reproducer
citation-style: https://www.zotero.org/styles/elsevier-with-titles
reference-section-title: References
references:
  - id: trapani15
    type: article-journal
    author:
      family: Trapani
      given: Lorenzo
    title: Testing for (in)finite moments
    container-title: Journal of Econometrics
    issued:
      - year: 2015
  - id: silver86
    type: book
    author:
      family: Silverman
      given: Bernard W.
    title: Density Estimation for Statistics and Data Analysis
    issued:
      - year: 1986
  - id: robertson74
    type: article-journal
    author:
    - family: Robertson
      given: Tim
    - family: Cryer
      given: Jonathan D
    issued:
      - year: 1974
    title: An iterative procedure for estimating the mode
    container-title: Journal of the American Statistical Association
    volume: 69
    issue: 348
...

# Testing

This is a test[@trapani15] for CSL[@silver86] display options[@robertson74].

# Compiling

Run this to compile: `pandoc --citeproc test.md -o test.pdf`
```
