### ISSUE TITLE
Bibliographies/punctuation: `?’.` fails to be transformed to `?’`

### ISSUE THREAD

**Issue by njbart** [jgm/pandoc#7372]
When formatting titles in reference lists, pandoc usually removes “superfluous“ punctuation: `?.` becomes `?`, `!.` becomes `!`.

This does not work as expected, however, when titles are enclosed in quotation marks, and the locale is set to, e.g., `en-GB`, where the final full stop/period is placed *after* the closing quotation mark. (Formatting of the book item, shown for comparison, is as expected with `en-GB`.)

```
pandoc -s --citeproc -t plain << EOT

Foo [@item1; @item2].

---
references:
- id: item1
  type: book
  author:
    - family: Doe
      given: Jane
  issued: 2020
  title: The title?
  publisher: The Publisher
- id: item2
  type: article-journal
  author:
    - family: Doe
      given: Jane
  issued: 2021
  title: The title?
  container-title: The Journal
reference-section-title: References
lang: en-GB
...
EOT
```

Actual output:

```
Foo (Doe 2020, 2021).

References

Doe, Jane. 2020. The Title? The Publisher.

———. 2021. ‘The Title?’. The Journal.
```

Expected output:

```
Foo (Doe 2020, 2021).

References

Doe, Jane. 2020. The Title? The Publisher.

———. 2021. ‘The Title?’ The Journal.
```

Zotero/citeproc-js, using `chicago-author-date.csl`, and (export) language set to “English (UK)” exports an equivalent title of a journal article as expected, i.e., without a full stop after the closing quotation mark.
