### ISSUE TITLE
Inline YAML references are always fully listed - disregarding actual usage

### ISSUE THREAD

**Issue by mjfs** [jgm/pandoc#7378]
Pandoc generates full bibliography list (disregarding the actual usage) of references when those are entered directly in the YAML header (or set in Lua filter). When that same list of references is contained in external file the actual usage is respected.

The following two examples should behave the same:

**Example (1)**

```markdown
---
bibliography: [references.yaml]
---

Bibliography list is not attached since there are no citations in the document.
```

Content of the `references.yaml` file:

```yaml
---
references:
-   id: ref1
    author:
    -   literal: John Doe
    issued: 2021-06-13
    title: Pandoc Test
...
```

**Example (2)**

```markdown
---
references:
-   id: ref1
    author:
    -   literal: John Doe
    issued: 2021-06-13
    title: Pandoc Test
---

Bibliography list (with 1 item) is attached despite there being no citations in the document.
```
