### ISSUE TITLE
Cannot use --self-contained with "bullet-proof web fonts", such as Computer Modern (aka LaTex-like)

### ISSUE THREAD

**Issue by kennknowles** [jgm/pandoc#739]
As a workaround for old version of IE, the [bullet proof approach to @font-face](http://paulirish.com/2009/bulletproof-font-face-implementation-syntax/) involves a hackish use of `?#iefix` to fool the old browser into ignoring the remainder of the attribute. [A more concise description](http://stackoverflow.com/questions/8050640/how-does-iefix-solve-web-fonts-loading-in-ie6-ie8) of just the end result of that essay was given on Stack Overflow.

Example:

``` css
@font-face {
        font-family: 'Computer Modern Serif';
        src: url('cmunrm.eot');
        src: url('cmunrm.eot?#iefix') format('embedded-opentype'),
                 url('cmunrm.woff') format('woff'),
                 url('cmunrm.ttf') format('truetype'),
                 url('cmunrm.svg#cmunrm') format('svg');
        font-weight: normal;
        font-style: normal;
}
```

Using `pandoc --self-contained` when incorporating such CSS results in an error like

```
pandoc: /usr/local/share/pandoc-1.10.0.5/data/stylesheets/../fonts/ComputerModern/Serif/cmunrm.eot?#iefix: openBinaryFile: does not exist (No such file or directory)
make: *** [paper.html] Error 1
```

Perhaps pandoc is treating the URL as a path, rather than taking the path portion of the URL? According to pandoc documentation it is falling back to the global directory after failing to find the font in the local directory, where it actually resides.

This may be particularly interesting because it prevents `--self-contained` use of the [Computer Modern web fonts](http://www.checkmyworking.com/cm-web-fonts/) for getting your HTML to look like a nice LaTeX paper.

(I am transitioning to pandoc as my source format for all drafts!)
