### ISSUE TITLE
line numbers are not shown in revealjs format - CSS issue

### ISSUE THREAD

**Issue by cderv** [jgm/pandoc#7634]
Example: 

````markdown
---
title: "test line number"
theme: white
---

## Line numbered

```{.r .number-lines}
1 + 1
2 + 2
3 + 3
```
````

If you create a reveal presentation using `pandoc -t revealjs -s -o reveal.html test.md`, the resulting HTML source will have correctly the `<a>` tags with number line but there are not shown in the browser. 

![image](https://user-images.githubusercontent.com/6791940/138271464-e4f310d9-1ca5-43b4-aa86-afb756f3b829.png)

I believe there is a CSS issue / conflict betwenn the one of Pandoc (skylighting?) and RevealJS. 

I think this is similar to https://github.com/jgm/pandoc/issues/6625 and 
````css
.sourceCode {
  overflow: visible
}
````
is necessary for numberLines to work. 

However, in reveal format, it will be overwritten by revealjs CSS rules. Especially 
````css
.reveal pre code {
    display: block;
    padding: 5px;
    overflow: auto;
    max-height: 400px;
    word-wrap: normal;
}
````
which has a higher precedence 

I think there should be a specific rule for reveal format
````css
.reveal .sourceCode {
  overflow: visible
}
````

I don't know if it should be in Pandoc or in skylighting (which I think introduce the css)

Locally, inserted this rules, fix the issue.
![image](https://user-images.githubusercontent.com/6791940/138271511-3c7663f2-e1f1-4b68-9ecb-0fe43b2e1860.png)
