### ISSUE TITLE
pandoc 2.16.2 does not compile with ghc 9.2.1

### ISSUE THREAD

**Issue by andrewufrank** [jgm/pandoc#7783]
There was a, perhaps related, bug report with no text:  Fix build on GHC 9.2 #7645 

**Explain the problem.**
Compilation is not possible, because dependency `memory-0.16`  is not ready for base 4.16. 

```
cabal install pandoc
Resolving dependencies...
cabal: Could not resolve dependencies:
[__0] trying: pandoc-2.16.2 (user goal)
[__1] trying: zlib-0.6.2.3 (dependency of pandoc)
[__2] trying: yaml-0.11.7.0 (dependency of pandoc)
[__3] trying: transformers-0.5.6.2/installed-0.5.6.2 (dependency of yaml)
[__4] trying: time-1.11.1.1/installed-1.11.1.1 (dependency of pandoc)
[__5] trying: http-client-tls-0.3.5.3 (dependency of pandoc)
[__6] trying: tls-1.5.6 (dependency of http-client-tls)
[__7] trying: x509-1.7.5 (dependency of tls)
[__8] next goal: memory (dependency of http-client-tls)
[__8] rejecting: memory-0.16.0 (conflict: transformers =>
base==4.16.0.0/installed-4.16.0.0, memory => base<4.16)
[__8] rejecting: memory-0.15.0 (conflict: transformers =>
base==4.16.0.0/installed-4.16.0.0, memory => base>=4.9 && <4.15)
[__8] rejecting: memory-0.14.18, memory-0.14.17 (conflict: transformers =>
base==4.16.0.0/installed-4.16.0.0, memory => base>=4.9.0.0 && <4.13)
[__8] rejecting: memory-0.14.16 (conflict: transformers =>
base==4.16.0.0/installed-4.16.0.0, memory => base>=4 && <4.12)
[__8] rejecting: memory-0.14.15 (conflict: transformers =>
base==4.16.0.0/installed-4.16.0.0, memory => base>=4.9 && <4.12)
[__8] rejecting: memory-0.14.14, memory-0.14.13, memory-0.14.12,
memory-0.14.11, memory-0.14.10, memory-0.14.9 (conflict: transformers =>
base==4.16.0.0/installed-4.16.0.0, memory => base>=4.7 && <4.13)
[__8] rejecting: memory-0.14.8, memory-0.14.7, memory-0.14.6 (conflict:
transformers => base==4.16.0.0/installed-4.16.0.0, memory => base>=4 && <4.11)
[__8] rejecting: memory-0.14.5 (conflict: tls => memory>=0.14.6)
[__8] skipping: memory-0.14.4, memory-0.14.3, memory-0.14.2, memory-0.14.1,
memory-0.14, memory-0.13, memory-0.12, memory-0.11, memory-0.10, memory-0.9,
memory-0.8, memory-0.7, memory-0.6, memory-0.5, memory-0.4, memory-0.3,
memory-0.2, memory-0.1 (has the same characteristics that caused the previous
version to fail: excluded by constraint '>=0.14.6' from 'tls')
[__8] fail (backjumping, conflict set: http-client-tls, memory, tls,
transformers)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, memory, tls, pandoc,
http-client-tls, yaml, x509, transformers, pandoc:setup.Cabal, time, deepseq,
array, zlib
Try running with --minimize-conflict-set to improve the error message.

frank@bhutan:~$ ghc --version
The Glorious Glasgow Haskell Compilation System, version 9.2.1
```

**Pandoc version?**
What version of pandoc are you using, on what OS?

```
uname -a 
Linux bhutan 5.10.0-10-amd64 #1 SMP Debian 5.10.84-1 (2021-12-08) x86_64 GNU/Linux
```
Thank you for maintaining a wonderful tool!

**Comment by jgm** [comment]
Since this involves a downstream dependency (memory), there's nothing we can do on pandoc's side.  All the needed changes to pandoc have been made.

You can get farther by using `--allow-newer`, but the build will still stumble on basement, which needs to be updated for ghc 9.2.1.
Here's the holdup (unresponsive maintainer):
https://github.com/haskell-foundation/foundation/pull/555

**Comment by jgm** [comment]
Btw, our dependency on basement is via the `connection` package.
If we could find an alternative to that, maybe we  could avoid it.

**Comment by jgm** [comment]
Here's a project file you can use to build with ghc 9.2.1:
```
cabal install --project-file=cabal.project.ghc921
```
where `cabal.project.ghc921` is:
```
packages: pandoc.cabal
tests: True
flags: +embed_data_files
constraints: aeson >= 2.0.1.0

allow-newer:
  base

source-repository-package
  type: git
  location: https://github.com/jgm/texmath.git
  tag: 46df85d747f4f233157d3476683264232a4f58be

source-repository-package
  type: git
  location: https://github.com/jgm/commonmark-hs
  tag: 4d460b206e0b1872376db86cadf7a4567eeddaed
  subdir: commonmark-pandoc

source-repository-package
  type: git
  location: https://github.com/jgm/ipynb.git
  tag: 00246af10885c2ad4413ace4f69a7e6c88297a08

source-repository-package
  type: git
  location: https://github.com/tfausak/hs-memory
  tag: 3cf661a8a9a8ac028df77daa88e8d65c55a3347a

source-repository-package
  type: git
  location: https://github.com/TomMD/foundation
  tag: 0bb195e1fea06d144dafc5af9a0ff79af0a5f4a0
  subdir: basement

source-repository-package
  type: git
  location: https://github.com/josephcsible/cryptonite
  tag: 3b081e3ad027b0550fc87f171dffecbb20dedafe
```
