### ISSUE TITLE
Parsing of macros with optional argument at the end in `beamer_presentation`

### ISSUE THREAD

**Issue by samcarter** [jgm/pandoc#7867]
As previously reported at https://github.com/rstudio/rmarkdown/issues/2294, if `beamer_presentation` is specified as output, macros with an optional argument at the end get incorrectly parsed to tex.  

Take for example the following example with `\setbeamertemplate{footline}[frame number]` in the header-includes:

```
---
title: "**TITLE**"
subtitle: "Subtitle"
author: "Name"
institute: ""
date: January 25, 2022
output:
  beamer_presentation:
    keep_tex: true
header-includes:
  - \setbeamertemplate{footline}[frame number]
---

test
```

The resulting .tex file will have 

```
\setbeamertemplate{footline}{[}frame number{]}
```

instead of

```
\setbeamertemplate{footline}[frame number]
```

If I change the output to something else, the macro will be parsed correctly:

```
---
title: "**TITLE**"
subtitle: "Subtitle"
author: "Name"
institute: ""
date: January 25, 2022
output:
  pdf_document:
    keep_tex: true
header-includes:
  - \usepackage{beamerarticle}
  - \setbeamertemplate{footline}[frame number]
---

test
```

I tested this with the following environment:

```
R version 4.1.1 (2021-08-10)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Big Sur 11.6.1, RStudio 2021.9.0.351

Locale: en_US.UTF-8 / en_US.UTF-8 / en_US.UTF-8 / C / en_US.UTF-8 / en_US.UTF-8

Package version:
  base64enc_0.1.3   bslib_0.3.1       digest_0.6.29     evaluate_0.14     fastmap_1.1.0     fs_1.5.2          glue_1.6.1        graphics_4.1.1   
  grDevices_4.1.1   highr_0.9         htmltools_0.5.2   jquerylib_0.1.4   jsonlite_1.7.3    knitr_1.37        magrittr_2.0.1    methods_4.1.1    
  R6_2.5.1          rappdirs_0.3.3    rlang_0.4.12      rmarkdown_2.11.12 sass_0.4.0        stats_4.1.1       stringi_1.7.6     stringr_1.4.0    
  tinytex_0.36      tools_4.1.1       utils_4.1.1       xfun_0.29         yaml_2.2.2       

Pandoc version: 2.17.0.1
```
