### ISSUE TITLE
Docx writer: support various citations like Zotero, EndNote, Mendeley, and native Word field

### ISSUE THREAD

**Issue by jooyoungseo** [jgm/pandoc#7893]
Once various citations in docx are supported (#7840, #7875, #7886, and #7889), could we consider supporting these citations in docx writer for round-trip conversion?

For example, could we specify the citation field type for docx output like below?:

``` yaml

---
bibliography: references.bib
csl: apa7.csl
cite
link-citations: false|hyperlink|native|zotero|endnote|mendeley
---

```

This will allow seamless collaboration between Pandoc users and those using other popular reference management tools in docx.

We may want to keep `link-citations: true` as a hyperlink while allowing other options like Zotero, etc. This will also address the issue mentioned in #6078.
