### ISSUE TITLE
Better handling of bibtex in filecontents environment

### ISSUE THREAD

**Issue by jgm** [jgm/pandoc#7896]
It is possible to include bibtex directly in a tex file using the filecontents environment:
```tex
\documentclass{article}
\usepackage{filecontents}

\begin{filecontents}{jobname.bib}
@book{author_book,
title = {Book's title},
author = {Author, Some},
location = {The City},
publisher = {Publisher},
date = {2005},
}
\end{filecontents}

\usepackage[style=authoryear,backend=bibtex]{biblatex} %backend tells biblatex what you will be using to process the bibliography file
\addbibresource{jobname.bib}

\begin{document}
\nocite{*}
\printbibliography
\end{document}
```
Pandoc currently handles the filecontent environment by keeping a virtual file system while reading LaTeX, so the contents can be retrieved later by commands that look for this file; this works for some kinds of things, e.g. includes, but it doesn't help much with bibtex.

Suggestion:  modify filecontents handling as follows.  If the filename ends with `.bib`, then parse the bibtex into `references` metadata, adding it to the metadata.
Thus, e.g., if you converted the above file to markdown, you'd get:
```
---
nocite: "[@*]"
references:
- author:
  - family: Author
    given: Some
  id: author_book
  issued: 2005
  publisher: Publisher
  title: Book's title
  type: book
---
```
