### ISSUE TITLE
Raw header-incluses

### ISSUE THREAD

**Issue by phmarek** [jgm/pandoc#7926]
I'm running `pandoc         2.17.1.1-1   amd64` on Debian.

I've got a few HTML files that I convert to tex via my own template; also, I'd like to expand a few variables in the template via a `metadata.yaml` file:

```yaml
---
title: my title
author:
- XYZ
- ABC
header-includes:
- |
  ```{=latex}
  \setlength\LTleft\parindent
  \setlength\LTright\fill
  \AddToHook{cmd/section/before}{\clearpage}
  ```
# vim: set et :
---
```

According to `MANUAL.txt`, https://github.com/jgm/pandoc/issues/3300, https://github.com/jgm/pandoc/issues/2139, and/or https://github.com/jgm/pandoc/commit/2b34337a9cf8b025914e8219498b4c0258772be0 this is the exact syntax I should be using; still, it doesn't work.

The authors and the title are correctly replaced in the template -- but then I get

```tex
\texttt{\{=latex\}\ \textbackslash{}setlength\textbackslash{}LTleft\textbackslash{}parindent\ \textbackslash{}setlength\textbackslash{}LTright\textbackslash{}fill\ \textbackslash{}AddToHook\{cmd/section/before\}\{\textbackslash{}clearpage\}}
```

instead of the raw data.

The command line (broken for readability) is
```
pandoc --metadata-file=metadata.yaml -f html <html files> --default-image-extension=svg  --variable <some>
   --extract-media <dir1> --extract-media <dir2> --number-sections --toc --pdf-engine=xelatex  --template=<template file>
   --standalone -t latex -o <output>
```

I also tried `html+raw_attribute`, but despite `raw_attribute` being listed as `generic` it's not accepted with `html`.

Is that a recent regression, or am I just not understanding how to use pandoc?

Thank you so much for your help!!
