### ISSUE TITLE
Allow defaults file to be specified in YAML header

### ISSUE THREAD

**Issue by d12bb** [jgm/pandoc#7977]
To use defaults files for specifying templates etc., the only possible way currently is using the command line option. This poses problems for using from within editors (like Zettlr or as makeprg in Vim), as one has to add specific command line options (`-d foo`) for every file. If a `defaults:` key in a file's YAML header was allowed (maybe only with `--defaults-from-infile` or similar for security reasons), it could stand alone and customizing the Pandoc command line for every type of file would only still be necessary for edge cases.

This was already discussed in [this comment](https://github.com/jgm/pandoc/issues/5870#issuecomment-708497494) and following, but as #5870 is basically the opposite request and there is no response by @jgm on this topic, I'm opening a separate issue for what I consider to be a separate request.

## Sample

```yaml
---
title: Why Pandoc is great
author: Me, obviously
defaults: presentation
---

It just is!
```
or
```yaml
---
title: Thesis
author: me, again
defaults: thesis
---

In a not to far future …
```

## Alternatives
There are tools like pandocomatic or panrun, which are much more powerful, but most times this power is not needed. Also, imo there should be no need for a third party tool for such a simple task.

For nVim, I created this pandoc.lua compiler plugin, which does exactly what I propose above, but only in Neovim:
```lua
local defaults = vim.fn.matchlist(vim.fn.getline(vim.fn.search('^defaults:', 'n')), '^defaults:\\s*\\(.*\\)$')[2]
defaults = defaults and ' -d '..defaults or ''
vim.bo.makeprg = 'pandoc' .. defaults .. ' -o "%:p:r.pdf" "%:p"'
```
