### ISSUE TITLE
Revealjs columns not sizing correctly in Pandoc 2.19

### ISSUE THREAD

**Issue by jjallaire** [jgm/pandoc#8232]
We've noticed that the behavior of `.columns` in Reveal JS has changed in Pandoc 2.19. Consider the following document:

````markdown
---
title: "Presentation"
---

## Columns

:::: {.columns}

::: {.column width="20%"}
Left column (20%)
:::

::: {.column width="80%"}
Right column (80%)
:::

::::
````

In Pandoc 2.19 we get this CSS in the head:

```css
 div.columns{display: flex; gap: min(4vw, 1.5em);}
 div.column{flex: 1;}
```

And this HTML written for the columns:

```html
<div class="columns">
  <div class="column" style="width:20%;">
    <p>Left column (20%)</p>
  </div><div class="column" style="width:80%;">
    <p>Right column (80%)</p>
  </div>
</div>
```

Which results in the columns not respecting the width:

<img width="789" alt="Screen Shot 2022-08-17 at 5 00 23 PM" src="https://user-images.githubusercontent.com/104391/185242160-97ee4087-0398-4669-9f1f-fb72ea029611.png">

In contrast, Pandoc 2.18 does not use flexbox (and yields the expected behavior via the `width` style):

```css
div.column{display: inline-block; vertical-align: top; width: 50%;}
```

I was able to get the correct behavior in Pandoc 2.19 by modifying the generated `.columns` HTML as follows:

```html
<div class="columns">
<div class="column" style="flex: 0.2;">
<p>Left column (20%)</p>
</div><div class="column" style="flex: 0.8;">
<p>Right column (80%)</p>
</div>
</div>
```
