### ISSUE TITLE
Prepending curly braces to suffix without locator (`[@smith{}, 99 years later]`) still interprets a page reference in citeproc (`(Smith & Crick, 1953, p., 99 years later)`)

### ISSUE THREAD

**Issue by mtorressahli** [jgm/pandoc#8288]
Hi

I'm trying to add a citation with a suffix that includes a comma and without locator, as in the third example of the [citations extension in the manual](https://pandoc.org/MANUAL.html#extension-citations) where it says

> In complex cases, you can force something to be treated as a locator by enclosing it in curly braces or prevent parsing the suffix as locator by prepending curly braces:
> 
> [@smith{ii, A, D-Z}, with a suffix]
> [@smith, {pp. iv, vi-xi, (xv)-(xvii)} with suffix here]
> [@smith{}, 99 years later]

The first and third example seems to not work as expected (unless in the first one the `ii` is expected to be read by default as page). I'm interested particularly in the third case, as I want to include a suffix that includes a comma without including a locator. In that case (`[@smith{}, 99 years later]`), `citeproc` produces an empty page reference (`(Smith & Crick, 1953, p., 99 years later)`) instead of omitting the locator (`(Smith & Crick, 1953, 99 years later)`).

I run the code below with the command `pandoc --from markdown --to plain --citeproc --no-highlight` in `https://pandoc.org/try/`

I've attached [apa7.zip](https://github.com/jgm/pandoc/files/9537180/apa7.zip) with the `apa7.csl` I'm using.

### Code

```
---
csl: 'apa7.csl'
references:
- type: article-journal
  id: WatsonCrick1953
  author:
  - family: Watson
    given: J. D.
  - family: Crick
    given: F. H. C.
  issued:
    date-parts:
    - - 1953
      - 4
      - 25
  title: 'Molecular structure of nucleic acids: a structure for
    deoxyribose nucleic acid'
  title-short: Molecular structure of nucleic acids
  container-title: Nature
  volume: 171
  issue: 4356
  page: 737-738
  DOI: 10.1038/171737a0
  URL: https://www.nature.com/articles/171737a0
  language: en-GB
---

[@smith{ii, A, D-Z}, with a suffix]

[@smith, {pp. iv, vi-xi, (xv)-(xvii)} with suffix here]

[@smith{}, 99 years later]
```

## Expected result (**emphasis** added)

> **(Smith & Crick, 1953, ii, A, D–Z, with a suffix)**
> 
> (Smith & Crick, 1953, pp. iv, vi–xi, (xv)–(xvii) with suffix here)
> 
> **(Smith & Crick, 1953, 99 years later)**
> 
> Smith, J. D., & Crick, F. H. C. (1953). Molecular structure of nucleic
> acids: a structure for deoxyribose nucleic acid. Nature, 171(4356),
> 737–738. https://doi.org/10.1038/171737a0

## Obtained output (**emphasis** added)

> **(Smith & Crick, 1953, pp. ii, A, D–Z, with a suffix)**
> 
> (Smith & Crick, 1953, pp. iv, vi–xi, (xv)–(xvii) with suffix here)
> 
> **(Smith & Crick, 1953, p., 99 years later)**
> 
> Smith, J. D., & Crick, F. H. C. (1953). Molecular structure of nucleic
> acids: a structure for deoxyribose nucleic acid. Nature, 171(4356),
> 737–738. https://doi.org/10.1038/171737a0

Many thanks!
