### ISSUE TITLE
citeproc works with json but not with (apparently) identical yaml

### ISSUE THREAD

**Issue by little-flag** [jgm/pandoc#8366]
Not sure if this is a bug or my ignorance. However, my citeproc conversion works with a json file but not with an (as far as I can tell) identical yaml file.

In other words, this works fine:
```
pandoc test.md -o test.docx --citeproc --bibliography Lukacs.json
```

But this raises an error: 
```
pandoc test.md -o test.docx --citeproc --bibliography Lukacs.yaml
-> [WARNING] Citeproc: citation Lukacs1989 not found
```

Here is the json, which works:
```
[
  {
    "author" : [
      {
        "given" : "Georg",
        "family" : "Lukács"
      }
    ],
    "issued" : {
      "date-parts" : [
        [
          "1989"
        ]
      ]
    },
    "ISBN" : "978-0-85036-378-4",
    "id" : "Lukacs1989",
    "publisher-place" : "London",
    "title" : "The Historical Novel",
    "publisher" : "Merlin",
    "type" : "book"
  }
]
```

And here is the yaml (produced by converting the json with `yj`), which doesn’t:
```
- author:
    - given: Georg
      family: Lukács
  issued:
    date-parts:
      - - "1989"
  ISBN: 978-0-85036-378-4
  id: Lukacs1989
  publisher-place: London
  title: The Historical Novel
  publisher: Merlin
  type: book

```

FWIW my reason for wanting to use the yaml version is that I need to concatenate a large number of bibliography files together and this is tricky (and comparatively slow) with json.

pandoc 2.19.2
macOS 12.6
