### ISSUE TITLE
Flexbox in CSS prevents EPUB from opening on some e-readers

### ISSUE THREAD

**Issue by denisftw** [jgm/pandoc#8379]
It seems that in this [change](https://github.com/jgm/pandoc/commit/0e8f424d9ef29175a12e8efb40e91a63aa939da1) the embedded CSS was modernized to use flexbox. However, it makes EPUB unreadable on some old e-readers, i.e on my PocketBook Pro 912 (with latest firmware). I'm not sure what was the motivation behind this change, but I don't see any attempts to use flexbox in EPUB-books produced by professional book publishers, i.e O'Reilly or No Starch. Not surprisingly, I can easily open their books but not the ones produced with `pandoc`.

Maybe it's worth reconsidering giving that not opening the book is already pretty bad. Alternatively, I would appreciate if there was a way to alter the inline CSS during generation.

Using `2.19.2` of pandoc on vanilla Arch:

```text
$ pandoc -s -t epub2 --metadata title="EPUB Test" test.md -o test.epub
```

where `test.md` consists of one paragraph of random text without any Markdown-markup.

**Comment by jgm** [comment]
@denisftw have you tried using `--css` to pass in custom CSS and override these?

I'm surprised that the reader fails to open the epub at all just because of some CSS it can't interpret!

@tarleb any thoughts?  I note that `data/epub.css` (which is used by default if they don't use `--css`) includes some things that duplicate what is added in `styles.html`, including the old-style declaration for div.column!  We should remove those duplications.  Or, maybe we should add in the old-style declarations for div.column and div.columns, to override the flexbox stuff for EPUBs, given the difficulties older readers have with flexbox.

**Comment by jgm** [comment]
@denisftw - could you try using `--css epub.css` with the following `epub.css`?
```css
/* This defines styles and classes used in the book */
body { margin: 5%; text-align: justify; font-size: medium; }
h1, h2, h3, h4, h5, h6 { text-align: left; }
/* For title, author, and date on the cover page */
h1.title { }
p.author { }
p.date { }
nav#toc ol,
nav#landmarks ol { padding: 0; margin-left: 1em; }
nav#toc ol li,
nav#landmarks ol li { list-style-type: none; margin: 0; padding: 0; }
a.footnote-ref { vertical-align: super; }
em, em em em, em em em em em { font-style: italic;}
em em, em em em em { font-style: normal; }
q { quotes: "“" "”" "‘" "’"; }
/* We don't use flexbox for columns due to lack of support in older readers. */
/* This means that only two columns are supported.  Removing the following */
/* two lines will cause flexbox to be used for columns, allowing more than */ 
/* two columns at the expense of support for older readers. */
div.columns{ display: block; }
div.column{ display: inline-block; vertical-align: top; width: 50%; }

@media screen { /* Workaround for iBooks issue; see #6242 */
  .sourceCode {
    overflow: visible !important;
    white-space: pre-wrap !important;
  }
}
```

**Comment by tarleb** [comment]
I fail to reproduce this with pandoc 2.19.2. This *was* a bug in 2.19.1, but it is fixed in the latest release as far as I can see.

**Comment by tarleb** [comment]
Scratch that, I do see this.

**Comment by tarleb** [comment]
Minor side note: my goal with #8275 is to make it possible to work around such an issue with a custom writer:

``` lua
local zip = pandoc.zip

function ByteStringWriter (doc, opts)
  local epub = pandoc.write(doc, 'epub3', opts)
  local archive = zip.toarchive(epub)
  archive.entries:map(function (entry)
      return zip.Entry(
        entry.path,
        entry:contents():gsub('\n%s*div.columns?%b{}', '')
      )
  end)
  return archive:tobytestring()
end
```

**Comment by jgm** [comment]
If the `--css` option described above doesn't work, another option would be using a custom template that replaces the `styles.html` partial.

In the end, though, we need to consider whether we should be producing output by default that will work on a wider variety of readers.

**Comment by denisftw** [comment]
Thanks for a quick response!

I tried overriding the styles with `-css` option, but it didn't help me. Apparently the reader trips at the moment it sees something flex-related and not when it consolidates styles. If I open the file with Sigil and manually replace the two inline CSS lines with styles from your file:

```css
div.columns{ display: block; }
div.column{ display: inline-block; vertical-align: top; width: 50%; }
```

then it works.

Changing templates also works, and indeed, I was able to produce the desired EPUB by specifying a different template. The easiest option was to simply put an adjusted (as above) version of `styles.html` into `~/.pandoc/templates`. In this case, the resulting EPUB will have the updated styles and I don't even need to do anything special in command line :)

Thanks for this suggestion!
