### ISSUE TITLE
Documentation Bug - epub-embed-font

### ISSUE THREAD

**Issue by edent** [jgm/pandoc#8455]
**Explain the problem.**

The documentation for `--epub-embed-font` is incorrect.

It gives as an example CSS:

```css
@font-face {
font-family: DejaVuSans;
font-style: normal;
font-weight: normal;
src:url("DejaVuSans-Regular.ttf");
}
```

The `src:url` is incorrect. It needs to be a relative path.  e.g.

```css
src:url("../fonts/DejaVuSans-Regular.ttf");
```

I've tested this in KOReader and Calibre. Both require the relative path.

As discussed in https://groups.google.com/g/pandoc-discuss/c/3VrefhiuVmM/m/I-NjsG_zBgAJ

**Pandoc version?**

* pandoc 2.19.2
* Ubuntu
