### ISSUE TITLE
Support software type in conversion to biblatex

### ISSUE THREAD

**Issue by jolars** [jgm/pandoc#8504]
When I am converting the following yaml file to biblatex via `pandoc citation.yml -f markdown -t biblatex -o citation.bib`, the output is a `misc` entry, but `software` is supported in biblatex, so it should be rendered as such. It is also missing the `version` entry.

`citation.yml`:

```yaml
---
references:
- id: Larsson_2016
  author:
    - family: Larsson
      given: Johan
  citation-key: Larsson_2016
  issued:
    - year: 2016
  medium: Windows
  title: 'qualpalr: Automatic Generation of Qualitative Color Palettes'
  type: software
  URL: https://cran.r-project.org/package=qualpalr
  version: 0.3.1
...
```

`citation.bib`:

```bibtex
@misc{
  Larsson_2016,
  author = {Larsson, Johan},
  title = {Qualpalr: {Automatic} {Generation} of {Qualitative} {Color} {Palettes}},
  date = {2016},
  url = {https://cran.r-project.org/package=qualpalr}
}
```

This is what I want to get, and is what for instance Zotero returns when I export using it's biblatex export:

```bibtex
@software{
  Larsson_2016,
  title = {qualpalr: Automatic Generation of Qualitative Color Palettes},
  url = {https://cran.r-project.org/package=qualpalr},
  version = {0.3.1},
  author = {Larsson, Johan},
  date = {2016},
}
```
