### ISSUE TITLE
<code> is hyphenized

### ISSUE THREAD

**Issue by mister-goo** [jgm/pandoc#8530]
**Explain the problem.**
After converting a markdown document to HTML, I noticed the text inside `<code>` is hyphenized. I suppose this hyphenation is undesired. I added a CSS to disable hyphenation:
```css
code {
  hyphens: manual;
}
```

**Pandoc version?**
Latest.
