### ISSUE TITLE
Discrepancy between docs and code for babelfonts

### ISSUE THREAD

**Issue by frederik-elwert** [jgm/pandoc#8697]
Commit 9b04036f6b0745c6ce0cb027683e94b648da3a9c added a `babelfonts` YAML metadata entry for configuring additional fonts for specific languages. However, in the commit, there seems to be a discrepancy between the documentation and the template code:

The original proposal suggested a YAML structure like this:

```yaml
babelfonts:
    - language: russian
      font: Noto Serif
    - language: chinese
      font: Noto Serif CJK TC
```

And this is what is in fact implemented in the template.

However, the docs now suggest this syntax:

```yaml
     ---
     babelfonts:
       chinese-hant: "Noto Serif CJK TC"
       russian: "Noto Serif"
     ...
```

I do think this simpler syntax is much more elegant. The original proposal would be easier to extend if more advanced settings should be passed to `\babelfont`, like the font family (`rm`, `sf` or `tt`) or font options like the renderer. But these are currently not used, and I think most cases are well covered by the simpler syntax. (And for advanced use cases, a custom template would still be possible.)

So in order to bring the actual template code on par with the documentation, the template code needs to be changed slightly:

```patch
--- default.latex.orig	2023-03-15 09:56:01.073764936 +0100
+++ default.latex	2023-03-15 10:04:00.518842188 +0100
@@ -365,8 +365,8 @@
 $for(babel-otherlangs)$
 \babelprovide[import]{$babel-otherlangs$}
 $endfor$
-$for(babelfonts)$
-\babelfont[$babelfonts.language$]{rm}{$babelfonts.font$}
+$for(babelfonts/pairs)$
+\babelfont[$babelfonts.key$]{rm}{$babelfonts.value$}
 $endfor$
 % get rid of language-specific shorthands (see #6817):
 \let\LanguageShortHands\languageshorthands
```

**Comment by jgm** [comment]
Sorry -- my mistake!  But I agree, this is better anyway.

**Comment by jgm** [comment]
Actually, I now think your original idea was better, because it allows us to specify font-options, so I think I'll revert back to that and change the  docs accordingly.
```
babelfonts:
    - language: russian
      font: Noto Serif
      font-options:
        Numbers: OldStyle
    - language: chinese
      font: Noto Serif CJK TC
```
