### ISSUE TITLE
Subscript and superscript in EPUB

### ISSUE THREAD

**Issue by byo-books** [jgm/pandoc#9160]
**Explain the problem.**
The `sub` and `sup` element style is not configured properly.
Subscript and superscript are shown as normal in EPUB.
Adding the following styles to `epub.css` should fix the issue:

```css
sup {
  vertical-align: super;
  font-size: smaller;
}
sub {
  vertical-align: sub;
  font-size: smaller;
}
```

**Pandoc version?**
Latest.
