### ISSUE TITLE
Using ${USERDATA} or ${HOME} in Defaults Bibliography Metadata

### ISSUE THREAD

**Issue by iandol** [jgm/pandoc#9173]
# Explain the problem:

Given this defaults file:

```yaml
verbosity: INFO # verbose by default
citeproc: true
cite-method: citeproc
reference-links: true
metadata:
  bibliography: ${USERDATA}/Core.json # JSON faster than BIB, symlinked into Pandoc data dir
  citation-abbreviations: ${USERDATA}/cite-abbr.json # my journal abbreviations
  csl: apa.csl
  reference-section-title: Bibliography
  notes-after-punctuation: false
  link-citations: true
  link-bibliography: true
```

When I try to compile I get an error:

```
▶︎ pandoc -d refs -t latex -o tuftebook.tex ~/Code/dotpandoc/test-tufte.md
[INFO] Running filter citeproc
[INFO] Loaded apa-ian.csl from /Users/ian/.local/share/pandoc/csl/apa-ian.csl
File ${USERDATA}/cite-abbr.json not found in resource path
```

So `${USERDATA}` is not expanding, 

```yaml
verbosity: INFO # verbose by default
citeproc: true
cite-method: citeproc
reference-links: true
bibliography: ${USERDATA}/Core.json #JSON faster than BIB, symlinked into Pandoc data dir
citation-abbreviations: ${USERDATA}/cite-abbr.json # my journal abbreviations
metadata:
  csl: apa.csl
  reference-section-title: Bibliography
  notes-after-punctuation: false
  link-citations: true
  link-bibliography: true
```

So `bibliography` and `citation-abbreviations` have been moved out of `metadata`, then Pandoc finds the files:

```
▷ pandoc -d refs -t latex -o tuftebook.tex ~/Code/dotpandoc/test-tufte.md
[INFO] Running filter citeproc
[INFO] Loaded apa-ian.csl from /Users/ian/.local/share/pandoc/csl/apa-ian.csl
[INFO] Loaded /Users/ian/.local/share/pandoc/cite-abbr.json from /Users/ian/.local/share/pandoc/cite-abbr.json
[INFO] Loaded /Users/ian/.local/share/pandoc/Core.json from /Users/ian/.local/share/pandoc/Core.json
[INFO] Completed filter citeproc in 245 ms
```

According to the manual, we should use `metadata` for bibliography but when I do ${USERDATA} fails to expand. 

# Expected Result:

I would ideally hope we could use `${USERDATA}` within metadata too.

# Hoped for extension:

Apart from `bibliography` I would also wish we could use `${USERDATA}` or `${HOME}` for other custom metadata fields, for example I have a `copyright-image` field I'd like to link to my pandoc data directory so my defaults files do not contain absolute paths, but I cannot do this at present. Why is the use of `${USERDATA}` or `${HOME}` so restrictive?

# Pandoc version?

```
▶︎ pandoc --version
pandoc 3.1.9
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/ian/.local/share/pandoc
Copyright (C) 2006-2023 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```
