### ISSUE TITLE
problem fetching remote csl style after upgrade to pandoc 3.1.12.1

### ISSUE THREAD

**Issue by antonyeagle** [jgm/pandoc#9483]
I brewed the latest pandoc 3.1.12.1  just now and a file that was compiling before the upgrade now does not. When I try to fetch a remote .csl file by specifying `csl: <url>` in the YAML metadata block, I now receive an error.

When I use the following command line prompt `pandoc --citeproc demo.md -f markdown -t latex -o demo.tex demo.md`, I get this error:

```
Could not fetch http://www.zotero.org/styles/australasian-journal-of-philosophy
HttpExceptionRequest Request {
  host                 = "www.zotero.org"
  port                 = 80
  secure               = False
  requestHeaders       = []
  path                 = "/styles/australasian-journal-of-philosophy"
  queryString          = ""
  method               = "GET"
  proxy                = Nothing
  rawBody              = False
  redirectCount        = 10
  responseTimeout      = ResponseTimeoutDefault
  requestVersion       = HTTP/1.1
  proxySecureMode      = ProxySecureWithConnect
}
 (InternalException (HandshakeFailed (Error_Protocol "peer does not support Extended Main Secret" HandshakeFailure)))
```

This is the MWE I used to obtain that error:

```
---
title: Demo
csl: http://www.zotero.org/styles/australasian-journal-of-philosophy
references:
- type: article-journal
  id: WatsonCrick1953
  author:
  - family: Watson
    given: J. D.
  - family: Crick
    given: F. H. C.
  issued:
    date-parts:
    - - 1953
      - 4
      - 25
  title: 'Molecular structure of nucleic acids: a structure for
    deoxyribose nucleic acid'
  title-short: Molecular structure of nucleic acids
  container-title: Nature
  volume: 171
  issue: 4356
  page: 737-738
  DOI: 10.1038/171737a0
  URL: https://www.nature.com/articles/171737a0
  language: en-GB
---

A citation: [@WatsonCrick1953].

# References {-}
```
