### ISSUE TITLE
Cannot generate a standalone HTML document with no style.

### ISSUE THREAD

**Issue by ant-222** [jgm/pandoc#9921]
The *User Guide* does not seem to mention how to create an HTML document without any built-in style. Some hard-coded style is included in default of `--css`. I have namaged reduce the `<style>` to a minimum via `-cd`, which is clearly a hack. Please, provide a method of generating a purely styless standalone HTML document.

**Comment by jgm** [comment]
Here's the CSS that is included even if you use `--css`:
```css
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    /* The extra [class] is a hack that increases specificity enough to
       override a similar rule in reveal.js */
    ul.task-list[class]{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      font-size: inherit;
      width: 0.8em;
      margin: 0 0.8em 0.2em -1.6em;
      vertical-align: middle;
    }
    .display.math{display: block; text-align: center; margin: 0.5rem auto;}
```
This is not really *stylistic*.  It is needed to make the pandoc elements render as they are supposed to.  E.g. without the ul rules, task lists would render with bullets. If we didn't include this, we'd need to put these styles inline in the elements themselves.

But these can all be overridden with your own CSS included via `--css`.

If this CSS is a problem for you, you can always use a custom template, or, to globally suppress pandoc's styles, put an empty template called `styles.html` in the `templates` subdirectory of your user data directory.
