### ISSUE TITLE
Pandoc fails with `--natbib` and default pdf-engine

### ISSUE THREAD

**Issue by wenkokke** [jgm/pandoc#9963]
**Explain the problem.**
Assume the following documents:
- `sample.md`:
  ```md
  We all love the famous proof by @BenjaminHornigold [p. 42].
  But is it real?
  No. Probably not.
  ```
- `sample.bib`:
  ```bibtex
  @book{BenjaminHornigold,
    author = {Benjamin Hornigold},
    title  = {A proof of Pirate ipsum},
    year   = {1680},
  }
  ```

To illustrate the issue, let us run Pandoc with three  different configurations:

1.  `default.yaml`
    ```yaml
    input-files: [sample.md]
    output-file: natbib.pdf
    citeproc: true
    metadata:
      bibliography: sample.bib
    ```
    yields
    
    ![default](https://github.com/jgm/pandoc/assets/3983973/0c803f84-9417-4c1d-b984-a543f1b13c3e)

2.  `natbib.yaml`
    ```yaml
    input-files: [sample.md]
    output-file: natbib.pdf
    citeproc: true
    cite-method: natbib
    metadata:
      bibliography: sample.bib
    ```
    yields
    
    ![natbib](https://github.com/jgm/pandoc/assets/3983973/2d31a27d-7447-49be-b656-7ef7a820bd9e)

3.  `natbib-latexmk`
    ```yaml
    input-files: [sample.md]
    output-file: natbib.pdf
    citeproc: true
    cite-method: natbib
    metadata:
      bibliography: sample.bib
    pdf-engine: "latexmk"
    ```
    yields

    ![natbib-latexmk](https://github.com/jgm/pandoc/assets/3983973/f38a764a-4f7f-4abc-8799-9d6e7e30d84e)

In (1), Pandoc uses its default citation rendering, and everything works. In (3), Pandoc uses natbib and LaTeXmk, and everything works. In (2), Pandoc uses natbib and the pdf-engine defaults to pdfLaTeX. The bibliography is not included, and the citation is not resolved. Changing the target to LaTeX and manually running pdfLaTeX and bibTeX *does* work.

**Pandoc version?**
Running Pandoc 3.2.1 on macOS 13.

```
pandoc 3.2.1
Features: +server +lua
Scripting engine: Lua 5.4
User data directory: /Users/keri/.local/share/pandoc
Copyright (C) 2006-2024 John MacFarlane. Web: https://pandoc.org
This is free software; see the source for copying conditions. There is no
warranty, not even for merchantability or fitness for a particular purpose.
```
